### ISSUE TITLE
Can't execute features

### ISSUE THREAD

**Issue by kappa10j** [cucumber/cucumber-js#1010]
I run cucumberjs from my project directory (c:\project\node_modules\.bin) but I get the below error message.  

I followed the example here... https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ProfileLoader.<anonymous> (C:\temp\NextGen\MESS\node_modules\cucumber\lib
\cli\profile_loader.js:55:27)
    at next (native)
    at tryCatcher (C:\temp\NextGen\MESS\node_modules\bluebird\js\release\util.js
:16:23)
    at PromiseSpawn._promiseFulfilled (C:\temp\NextGen\MESS\node_modules\bluebir
d\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\temp\NextGen\MESS\node_modules\bluebird\js\rel
ease\promise.js:574:26)
    at Promise._settlePromise0 (C:\temp\NextGen\MESS\node_modules\bluebird\js\re
lease\promise.js:614:10)
    at Promise._settlePromises (C:\temp\NextGen\MESS\node_modules\bluebird\js\re
lease\promise.js:693:18)
    at Async._drainQueue (C:\temp\NextGen\MESS\node_modules\bluebird\js\release\
async.js:133:16)

**Comment by charlierudolph** [comment]
Does your project folder have a `cucumber.js` file in it? It appears that is what its trying to parse.

**Comment by kappa10j** [comment]
the cucumber.js is in the node_modules folder

My folder structire is

-node_modules
-Test
--Features
---feature.feature
---step_definitions
----steps.js
----support
-----world.js

Do I need cucumber.js at the project root?

**Comment by charlierudolph** [comment]
No but that is a configuration file if present. Where are you running from? (you should be in the `Test` folder)

**Comment by kappa10j** [comment]
C:\project\node_modules\.bin>cucumber-js
C:\project\node_modules\.bin\cucumber.js:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

I thought we need to run from the .bin

"Run ./node_modules/.bin/cucumber-js" --> https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md

**Comment by charlierudolph** [comment]
Your current working directory should be the directory that contains the features. `./node_modules/.bin/cucumber-js` should be the path to the executable from your project

**Comment by kappa10j** [comment]
thanks... rookie mistake
