### ISSUE TITLE
Errors thrown during test runs

### ISSUE THREAD

**Issue by achingbrain** [cucumber/cucumber-js#1032]
I sometimes see this crash from cucumber-js during test runs, usually when selenium-webdriver cannot reach chromedriver:

```
/path/to/my/project/node_modules/cucumber/lib/formatter/summary_formatter.js:54
      return _lodash2.default.includes([_status2.default.AMBIGUOUS, _status2.default.FAILED], testCase.result.status);
                                                                                                             ^

TypeError: Cannot read property 'status' of undefined
    at ProgressFormatter.isTestCaseFailure (/path/to/my/project/node_modules/cucumber/lib/formatter/summary_formatter.js:54:110)
    at /path/to/my/project/node_modules/cucumber/lib/formatter/summary_formatter.js:69:20
    at /path/to/my/project/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/path/to/my/project/node_modules/lodash/lodash.js:3001:24)
    at /path/to/my/project/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/path/to/my/project/node_modules/lodash/lodash.js:9359:14)
    at ProgressFormatter.logSummary (/path/to/my/project/node_modules/cucumber/lib/formatter/summary_formatter.js:68:24)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Master.onSlaveClose (/path/to/my/project/node_modules/cucumber/lib/runtime/parallel/master.js:120:31)
    at Interface.<anonymous> (/path/to/my/project/node_modules/cucumber/lib/runtime/parallel/master.js:106:15)
    at emitNone (events.js:91:20)
    at Interface.emit (events.js:185:7)
    at Interface.close (readline.js:319:8)
    at Socket.onend (readline.js:108:10)
    at emitNone (events.js:91:20)
```

**Comment by achingbrain** [comment]
I also sometimes see this one:

```
/path/to/my/project/node_modules/cucumber/lib/formatter/helpers/event_data_collector.js:103
      if (!step.attachments) {
               ^

TypeError: Cannot read property 'attachments' of undefined
    at EventDataCollector.storeTestStepAttachment (/path/to/my/project/node_modules/cucumber/lib/formatter/helpers/event_data_collector.js:103:16)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Master.parseSlaveLine (/path/to/my/project/node_modules/cucumber/lib/runtime/parallel/master.js:80:33)
    at Interface.<anonymous> (/path/to/my/project/node_modules/cucumber/lib/runtime/parallel/master.js:106:15)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:375:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:374:11)
    at Socket.ondata (readline.js:100:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

**Comment by achingbrain** [comment]
I don't work on the project in question any more. Maybe @paulwib or @customcommander could help out?

**Comment by paulwib** [comment]
We haven't seen this issue recently, so feel free to close.
