### ISSUE TITLE
JSON error on hook with console.log and --parallel

### ISSUE THREAD

**Issue by kozhevnikov** [cucumber/cucumber-js#1037]
Having a hook that logs something and running with the experimental parallel option produces a JSON error.

```
Before(() => { console.log('Before'); });
```

```
undefined:1
Before
^

SyntaxError: Unexpected token B in JSON at position 0
    at JSON.parse (<anonymous>)
    at Master.parseSlaveLine (/Users/ilya.kozhevnikov/Desktop/cucumber-pretty/node_modules/cucumber/lib/runtime/parallel/master.js:70:24)
    at Interface.<anonymous> (/Users/ilya.kozhevnikov/Desktop/cucumber-pretty/node_modules/cucumber/lib/runtime/parallel/master.js:102:15)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
cucumber-pretty ilya.kozhevnikov$ events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

**Comment by charlierudolph** [comment]
stderr will be passed through, thus if you use `console.error` this should work. We should add that to the docs
