### ISSUE TITLE
Unhandled rejection Error: (72:14): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'a textarea to enter query, close icon should be displayed'

### ISSUE THREAD

**Issue by arjun1092** [cucumber/cucumber-js#1061]
hi Team,

I'm getting the following error since morning. I had update protractor and cucumber to the latest versions today morning  to the following:  "protractor": "^5.3.1", "cucumber": "^4.1.0".

`Unhandled rejection Error: (72:14): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'a textarea to enter query, close icon should be displayed'
    at C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\cucumber\src\cli\helpers.js:63:13
    at Array.forEach (native)
    at C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\cucumber\src\cli\helpers.js:51:10
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\generators.js:201:15
    at getTestCases (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\cucumber\lib\cli\helpers.js:96:18)
    at C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\cucumber\src\cli\helpers.js:30:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Arjun_u\Desktop\VS_code_test\cucumber\ProtractorScripts\node_modules\bluebird\js\release\async.js:133:16)`

The wierd part is I cannot find a folder called as "node_modules\cucumber\src\cli\helpers.js:63:13
    at Array.forEach (native)" in the node_modules folder

**Comment by charlierudolph** [comment]
That’s an error that comes from parsing the “.feature” file. Looks like we need to wrap the error so you know what file the praying error happened on.

**Comment by charlierudolph** [comment]
In the meantime, can you search your feature files for the text highlighted in the error message (a textarea to enter query, ...) where the parsing error occurred.

**Comment by arjun1092** [comment]
hi @charlierudolph , The errors are displayed to be coming from node_modules folder.  how to pinpoint the feature file causing the issue ?

**Comment by charlierudolph** [comment]
As I noted in my previous comment, for now you search for the text in the error message: “a textarea to enter query, close icon should be displayed”. Hopefully that doesn’t appear too many times and gives you only a few files where you can search in looking for a syntax error.

I’ll work on updating the code so the message would in include the file name.

**Comment by arjun1092** [comment]
@charlierudolph  I don't have such a text in my test script. "“a textarea to enter query, close icon should be displayed”. "  That is the strangest thing and the folders corresponds ton "node_modules" folder in the test script folder.

**Comment by charlierudolph** [comment]
Hmm. Okay then, let me try and get out a release in the next couple hours that includes the file name in the error message when there is a parse failure and we can debug it further with that.

The stack trace doesn't include where the feature file that failed to parse is.

**Comment by charlierudolph** [comment]
4.2.1 is released. Please give that a try
