### ISSUE TITLE
`TypeError: Cannot read property 'line' of undefined` when I use `--language ru` option

### ISSUE THREAD

**Issue by DMShamonov** [cucumber/cucumber-js#1117]
When I reproduce an official [hellocucumber example ](https://docs.cucumber.io/guides/10-minute-tutorial/) step by step it's work fine. But when I change default language for feature files to `ru` and rename feature keywords to language specific keywords (for example `Feature` -> `Функция` and etc.) I catching error:
```
> cucumber-js --language ru

TypeError: Cannot read property 'line' of undefined
    at Object.generateEvents (/home/test/hellocucumber/node_modules/gherkin/lib/gherkin/generate_events.js:61:38)
    at /home/test/hellocucumber/node_modules/cucumber/lib/cli/helpers.js:81:36
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/vtest/hellocucumber/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/test/hellocucumber/node_modules/bluebird/js/release/generators.js:97:49)
    at /home/test/hellocucumber/node_modules/bluebird/js/release/generators.js:201:15
    at getTestCases (/home/test/hellocucumber/node_modules/cucumber/lib/cli/helpers.js:102:18)
    at /home/test/hellocucumber/node_modules/cucumber/lib/cli/helpers.js:50:39
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/test/hellocucumber/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/test/hellocucumber/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/test/hellocucumber/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/test/hellocucumber/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/test/hellocucumber/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/test/hellocucumber/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/test/hellocucumber/node_modules/bluebird/js/release/async.js:143:10)
npm ERR! Test failed.  See above for more details.
```
Environment: Ubuntu Server 16.04.5 LTS, nodejs 10.9.0, npm 6.2.0, cucumber-js 4.2.1

But when I do it on my Mac, it's work fine with `--language ru` option...

**Comment by MartinoBR** [comment]
I am reproducing the same example and English works fine, but when I change the language to Portuguese it presents the same error.
I update the gherskin, cucumber expressions but the error persists.

Environment: Ubuntu Desktop 18.10, nodejs 10.13.0, npm 6.4.1, cucumber-js 5.0.2, gherkin 6.0.15, cucumber-expressions 6.0.1

```
$ ./node_modules/.bin/cucumber-js --language pt
TypeError: Cannot read property 'line' of undefined
    at Object.generateEvents (/home/lucas/src/processo-de-software-em-php/node_modules/cucumber/node_modules/gherkin/lib/gherkin/generate_events.js:61:38)
    at /home/lucas/src/processo-de-software-em-php/node_modules/cucumber/lib/cli/helpers.js:81:36
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/generators.js:97:49)
    at /home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/generators.js:201:15
    at getTestCases (/home/lucas/src/processo-de-software-em-php/node_modules/cucumber/lib/cli/helpers.js:102:18)
    at /home/lucas/src/processo-de-software-em-php/node_modules/cucumber/lib/cli/helpers.js:50:39
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/lucas/src/processo-de-software-em-php/node_modules/bluebird/js/release/async.js:131:9)
```

**Comment by MartinoBR** [comment]
Running without language parameters works perfectly in both English and Portuguese, but if you pass the language parameter "cucumber-js --language pt" it displays the error "Can not read property 'line' of undefined".
@DMShamonov maybe remove language parameters works for your case too.

**Comment by DblK** [comment]
Any update for a fix for that one?

**Comment by charlierudolph** [comment]
The gherkin project went through some big changes. This has been fixed but having issues upgrading to the latest version. Created some issues on that project.

**Comment by davidjgoss** [comment]
7.0.0 is now released, see [the changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) for migration instructions. Thanks!
