### ISSUE TITLE
cannot find module 'features/step_definitions'

### ISSUE THREAD

**Issue by cormac-dunphy** [cucumber/cucumber-js#1142]
When i try to run a cucumber test I get back an error:
**************
Error: Cannot find module 'features/step_definitions/github.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /home/vagrant/src/pisces-web-ui/node_modules/cucumber/lib/cli/index.js:170:16
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (/home/vagrant/src/pisces-web-ui/node_modules/cucumber/lib/cli/index.js:169:24)
    at Cli.<anonymous> (/home/vagrant/src/pisces-web-ui/node_modules/cucumber/lib/cli/index.js:188:39)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/vagrant/src/pisces-web-ui/node_modules/bluebird/js/release/async.js:143:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pisces-web-ui@0.1.0 test: ` ./node_modules/.bin/cucumber-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pisces-web-ui@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-10-12T09_33_28_186Z-debug.log
****************
I am using example code from this repository on github for my features and step_definitions files: https://github.com/rquellh/testcafe-cucumber
cucumber:3.0.0
node:8.9.2
osx operating system

**Comment by Izhaki** [comment]
Which command do you run exactly?
Can you share your repo?

I fail to believe this is an issue with cucumber-js, so closing it. Will be happy to re-open once there are more details / some reasonable argument this has to do with this repo.
