### ISSUE TITLE
How to run feature-files/scenarios in parallel?

### ISSUE THREAD

**Issue by stavalfi** [cucumber/cucumber-js#1144]
I see open and closed issues about parallelism but no documentation.

Where can I find it?

When I run:
```javascript
cucumber-js --parallel 4 --world-parameters "{\"browser\": \"chrome\", \"url\": \"http://localhost:4200/#\"}"`
```
I get:
> Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at Socket._writeGeneric (net.js:761:5)
    at Socket._write (net.js:773:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at Master.startSlave (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\cucumber\lib\runtime\parallel\master.js:108:27)
    at C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\cucumber\lib\runtime\parallel\master.js:142:23
    at baseTimes (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\lodash\lodash.js:968:23)
    at Function.times (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\lodash\lodash.js:16108:20)
    at Master.run (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\cucumber\lib\runtime\parallel\master.js:141:24)
    at C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\cucumber\lib\cli\index.js:207:35
    at Promise._execute (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\promise.js:79:10)
    at Cli.<anonymous> (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\cucumber\lib\cli\index.js:206:17)
    at Generator.next (<anonymous>:null:null)
    at Generator.tryCatcher (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\stava\WebstormProjects\6.7_rh-front-end-automation\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)

**Comment by charlierudolph** [comment]
https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#parallel-experimental

**Comment by stavalfi** [comment]
Can you show me an example? It seems that my command is good:

```javascript
cucumber-js --parallel 4 --world-parameters "{\"browser\": \"chrome\", \"url\": \"http://localhost:4200/#\"}"
```

**Comment by qileilove** [comment]
is there any update for this topic？ from the doc 
```
you can run your scenarios in parallel with --parallel <NUMBER_OF_SLAVES>. Each slave is run in a separate node process and receives the following env variables:

CUCUMBER_PARALLEL - set to 'true'
CUCUMBER_TOTAL_SLAVES - set to the number of slaves
CUCUMBER_SLAVE_ID - ID for slave ('0', '1', '2', etc.)
```
so need to set the env variables, but how to do set up?

**Comment by jain-neeeraj** [comment]
@stavalfi have you tried upgrading cucumber js? as per documentation shared by @charlierudolph this issue might be caused by old version of cucumber js

**Comment by stavalfi** [comment]
no... 'm closing this issue because I'm not using cucumber (now)

**Comment by fergadipa** [comment]
> https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#parallel-experimental

does it work on you? can you give the example?

**Comment by charlierudolph** [comment]
Our windows CI recently started breaking with regards to parallel but I got it working again by switching internals. The next cucumber release may fix this.
