### ISSUE TITLE
'node' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by irshad413** [cucumber/cucumber-js#1145]
Hi all,

I am trying to build a maven framework where test scripts are executed through Protractor. I have used https://github.com/eirslett/frontend-maven-plugin to install Node and npm modules in to a working directory.

After that i used https://www.mojohaus.org/exec-maven-plugin/ to install node modules one by one like Protractor, Jasmine and Restler etc. Everything worked absolutely fine. Technically the node was available only in the folders where project is running. No need to install node in my machine. Please refer to https://github.com/irshad413/ProtractorMavenUiAndApi for the sample project created, it's working fine.

I thought of including Cucumber in the project and then the real problem started. I added an execution for Cucumber but when I do a maven install all other node modules are getting installed except for cucumber, below is my pom

[pom.txt](https://github.com/cucumber/cucumber-js/files/2498391/pom.txt)

And the error I am receiving is as below: 
> cucumber-expressions@6.0.1 postinstall C:\BackUp\testing\protractor\New folder\ProtractorMavenUiAndApi\node\node_modules\cucumber\node_modules\cucumber-expressions
> node scripts/postinstall.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cucumber-expressions@6.0.1 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cucumber-expressions@6.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-10-20T17_23_18_616Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)

Am I missing something. Please provide some suggestions.

**Comment by charlierudolph** [comment]
Wow that is an interesting setup. So cucumber-expressions lives [here](https://github.com/cucumber/cucumber/tree/master/cucumber-expressions/javascript) and has a post-install to build the source if needed.

If node is available where you ran `npm install`, I would expect it to be available when running the postinstall script. Not sure how to help as I don't know java nor the referenced plugin.

**Comment by irshad413** [comment]
And while investigating I installed Node.Js in my machine, thus make making node available in global level.
I don't see any issue afterwards. 
which means postinstall script is always referring to node in global level, rather than using available node. Does this information help to some extent. 

I am just trying to implement automation testing using protractor. Not very much familiar with node.js

**Comment by Izhaki** [comment]
I'm closing this issue due to:

- Inactivity.
- This is not an issue with cucumber-js it seems. It's environment related.
