### ISSUE TITLE
Error when importing step definitions from external library

### ISSUE THREAD

**Issue by vjrasane** [cucumber/cucumber-js#1146]
Hello,

I'm running a set of integration tests with cucumber-js and in an attempt to extract some of the step definitions to a reusable library project, I've run into a weird error message that I can't quite understand.

The situation is as follows:

 * Common step definitions are as CJS code in a library project
 * The library project is linked through Yarn link to the main test project
 * The main test project requires the common step definitions in its step definitions CJS code
 * When running cucumber-js from the command line, following error is thrown:

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.relative (path.js:499:5)
    at getDefinitionLineAndUri (C:\Users\vrasanen\Repositories\cucumber-import-issue\lib_pkg\node_modules\cucumber\lib\support_code_library_builder\build_helpers.js:150:28)
    at buildStepDefinition (C:\Users\vrasanen\Repositories\cucumber-import-issue\lib_pkg\node_modules\cucumber\lib\support_code_library_builder\build_helpers.js:116:32)
    at SupportCodeLibraryBuilder.defineStep (C:\Users\vrasanen\Repositories\cucumber-import-issue\lib_pkg\node_modules\cucumber\lib\support_code_library_builder\index.js:72:67)
    at Object.<anonymous> (C:\Users\vrasanen\Repositories\cucumber-import-issue\lib_pkg\index.js:5:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\vrasanen\Repositories\cucumber-import-issue\main_pkg\features\step_definitions\index.js:1:63)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at C:\Users\vrasanen\Repositories\cucumber-import-issue\main_pkg\node_modules\cucumber\lib\cli\index.js:170:16`

So this makes me wonder if cucumber-js supports this kind of functionality at all, or whether I have a wrong approach to it.

I've attached a zip file containing a minimal reproduction case (I would've created a Github repo, but its acting up for me right now for some reason). The steps to reproduce are:

[cucumber-import-issue.zip](https://github.com/cucumber/cucumber-js/files/2500853/cucumber-import-issue.zip)

1. extract zip
2. run 'yarn install' in both main_pkg and lib_pkg directories (lib_pkg is linked to main_pkg in its package.json)
3. run 'yarn test' in main_pkg directory

This should cause the same error to be thrown. 

Let me know if there are any additional details you require.

BR,
Ville

**Comment by dsole** [comment]
I have the same issue with the external library is linked with npm. It works fine when it's installed as normal, but not when linked.
From the little but of investigation I've done I believe its because when cucumber-js gets the path to the file it gets the linked source path, but expects/assumes it to be under to the root path of the project.

So if you had linked `C:\Code\reusable-lib\`  to `C:\Code\my-project\node_modules\reusable-lib\`  , when Cucumber gets the file path for the file `C:\Code\my-project\node_modules\reusable-lib\step-definitions.js`  the path provided is `C:\Code\reusable-lib\step-definitions.js`
The cucumber-js code assumes that the file path should be under `C:\Code\my-project\`  and this causes the errors.

As a workaround I have been installing the reusable library using its file path or a tarball (created using `npm pack`) but then you need to keep updating the files that get copied into your consuming project.

I haven't had a chance to look at actually fixing the bug yet.

**Comment by mwyld** [comment]
Is this something that can be fixed? this issue knocked me out for a few hours yesterday as the error is misleading and its a pain not being able to use `NPM link`

**Comment by charlierudolph** [comment]
Appears you found a workaround. This isn't something that cucumber supports or has documentation around. As you probably found the hard part is making sure the external library and the main project are using the same instance of cucumber.

I'd suggest the external library not directly import cucumber. Would probably be better to have the external library have an API of a function that is passed cucumber by the library that imports it.

```javascript
// external library
export function includeSteps({Given, When, Then}) {
  //...
}

// main project
includeSteps(require('cucumber'))
```

**Comment by pipobscure** [comment]
Just FYI, this is a solved problem in NodeJS. See https://nodejs.org/es/blog/npm/peer-dependencies/

So in this case the share module should declare a peer-dependency on cucumber-js and the main test-project should be the one with the dependency.
