### ISSUE TITLE
--parallel option throws errors

### ISSUE THREAD

**Issue by znevrly** [cucumber/cucumber-js#1164]
Hi,
running latest CucumberJs 5.1.0, Windows 10

cucumber-js --format progress --require lib --parallel 3

Output:

child_process.js:111                                                                                
  p.open(fd);                                                                                       
    ^                                                                                               
                                                                                                    
Error: EBADF: bad file descriptor, uv_pipe_open                                                     
    at Object.exports._forkChild (child_process.js:111:5)                                           
    at Object.setupChannel (internal/process.js:236:8)                                              
    at startup (bootstrap_node.js:74:14)                                                            
    at bootstrap_node.js:625:3                                                                      
child_process.js:111                                                                                
  p.open(fd);                                                                                       
    ^                                                                                               
                                                                                                    
Error: EBADF: bad file descriptor, uv_pipe_open                                                     
    at Object.exports._forkChild (child_process.js:111:5)                                           
    at Object.setupChannel (internal/process.js:236:8)                                              
    at startup (bootstrap_node.js:74:14)                                                            
    at bootstrap_node.js:625:3                                                                      
child_process.js:111                                                                                
  p.open(fd);                                                                                       
    ^                                                                                               
                                                                                                    
Error: EBADF: bad file descriptor, uv_pipe_open                                                     
    at Object.exports._forkChild (child_process.js:111:5)                                           
    at Object.setupChannel (internal/process.js:236:8)                                              
    at startup (bootstrap_node.js:74:14)                                                            
    at bootstrap_node.js:625:3

**Comment by znevrly** [comment]
This should be valid, it works OK without parallel parameter.

**Comment by znevrly** [comment]
I have verified that issue in on Windows only. Have Windows 10, on WSL Linux Ubuntu it works well.

**Comment by robert-fahey** [comment]
Also encountering this issue on Windows 10.

**Comment by charlierudolph** [comment]
Believe this is fixed in dfe69ede6bd05a58cfa226dbb0600e7f65bdf073. Will try to verify on windows 10

**Comment by charlierudolph** [comment]
Just released version 6. Please comment if this isn't resolved after updating
