### ISSUE TITLE
Summary and JSON formatters do not localize the scenario's keyword

### ISSUE THREAD

**Issue by nikolaas** [cucumber/cucumber-js#1215]
Hello!

I am trying to write cucumber's tests with Russian localization. I found that summary and JSON formatters do not localize the scenario's keyword.

## Steps to reproduce

1. Clone the example repository:
```
git clone https://github.com/nikolaas/cucumber-localization-issue-example.git
cd cucumber-localization-issue-example
```
2. Install dependencies:
```
npm install
```
3. Run cucumber's tests with the summary formatter:
```
npm run test:summary
```
4. Run cucumber's tests with the JSON formatter:
```
npm run test:json
```

## Expected result

I expect the formatters output the scenario's keyword localized in Russian: "Сценарий".

## Actual result

The formatters output the scenario's keyword that is not localized in Russian: "Scenario".

The output of the summary formatter (- actual, + expected):

```diff
Failures:

-1) Scenario: Поделить два числа # features/divide/divide.feature:5
+1) Сценарий: Поделить два числа # features/divide/divide.feature:5
   ✔ Дано калькулятор # features/divide/steps/divideTwoNumbers.js:4
   ✔ Если я делю 6 на 2 # features/divide/steps/divideTwoNumbers.js:6
   ✖ То результат равен 5 # features/divide/steps/divideTwoNumbers.js:10
       AssertionError
           + expected - actual

           -3
           +5

           at World.<anonymous> (/Users/nstupak/projects/icore/hellobdd/features/divide/steps/divideTwoNumbers.js:11:28)

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m00.005s
```

The output of the JSON formatter (- actual, + expected):

```diff
[
  {
    "keyword": "Функционал",
    "name": "Как пользователь, я хочу поделить два числа",
    "line": 3,
    "id": "как-пользователь,-я-хочу-поделить-два-числа",
    "tags": [],
    "uri": "features/divide/divide.feature",
    "elements": [
      {
        "id": "как-пользователь,-я-хочу-поделить-два-числа;поделить-два-числа",
-       "keyword": "Scenario",
+       "keyword": "Сценарий",
        "line": 5,
        "name": "Поделить два числа",
        "tags": [],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Дано ",
            "line": 6,
            "name": "калькулятор",
            "match": {
              "location": "features/divide/steps/divideTwoNumbers.js:4"
            },
            "result": {
              "status": "passed",
              "duration": 1000000
            }
          },
          {
            "arguments": [],
            "keyword": "Если ",
            "line": 7,
            "name": "я делю 6 на 2",
            "match": {
              "location": "features/divide/steps/divideTwoNumbers.js:6"
            },
            "result": {
              "status": "passed"
            }
          },
          {
            "arguments": [],
            "keyword": "То ",
            "line": 8,
            "name": "результат равен 5",
            "match": {
              "location": "features/divide/steps/divideTwoNumbers.js:10"
            },
            "result": {
              "status": "failed",
              "duration": 2000000,
              "error_message": "AssertionError\n    + expected - actual\n\n    -3\n    +5\n\n    at World.<anonymous> (/Users/nstupak/projects/icore/hellobdd/features/divide/steps/divideTwoNumbers.js:11:28)"
            }
          }
        ]
      }
    ]
  }
```

## Environment

* cucumber version 5.1.0.

**Comment by aurelien-reeves** [comment]
JSON formatter is deprecated in favor of [cucumber-messages](https://github.com/cucumber/cucumber/blob/master/messages/README.md).

Thank you for your contribution but we won't prioritize changes to code that we plan to remove.
