### ISSUE TITLE
Not working anymore: npm install cucumber

### ISSUE THREAD

**Issue by RoValentim** [cucumber/cucumber-js#1274]
Installation is not working anymore:

```
~/cucumber> npm install cucumber
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN API_TESTING@1.0.0 No repository field.

+ cucumber@6.0.5
updated 1 package and audited 24284 packages in 5.497s

10 packages are looking for funding
  run `npm fund` for details

found 100 vulnerabilities (13 low, 4 moderate, 83 high)
  run `npm audit fix` to fix them, or `npm audit` for details
~/cucumber> npm audit fix
npm WARN API_TESTING@1.0.0 No repository field.

up to date in 3.589s

11 packages are looking for funding
  run `npm fund` for details

fixed 0 of 100 vulnerabilities in 24284 scanned packages
  100 vulnerabilities required manual review and could not be updated

```

Versions
```
~/cucumber> node --version
v10.18.0
~/cucumber> npm --version
6.13.4
~/cucumber> cat /proc/version 
Linux version 5.3.12-2-default (geeko@buildhost) (gcc version 9.2.1 20190903 [gcc-9-branch revision 275330] (SUSE Linux)) #1 SMP Thu Nov 21 07:21:43 UTC 2019 (a6f6081)
```

**Comment by davidjgoss** [comment]
It looks like the install worked fine there, per:

```
+ cucumber@6.0.5
updated 1 package and audited 24284 packages in 5.497s
```

The vulnerabilities audit stuff doesn't prevent installation.

If you look in `node_modules` you should see that cucumber is there

**Comment by RoValentim** [comment]
I looked, but directory is empty.

I tried again and nothing.

**Comment by tolalitnegi** [comment]
I am also getting issue while installing latest version of cucumber on node 12.

- node -v 12.14.0
- npm -v 6.13.4

**$ npm install cucumber@6.0.5**

`
> fibers@1.0.15 install /mycode//node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:70:58: error: no template named 'Handle'
        void Reset(Isolate* isolate, Persistent<T>& persistent, Handle<T> handle) {
                                                                ^
../src/fibers.cc:83:7: error: variable has incomplete type 'void'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
             ^
../src/fibers.cc:83:26: error: use of undeclared identifier 'Handle'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                ^
../src/fibers.cc:83:33: error: 'T' does not refer to a value
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                       ^
../src/fibers.cc:82:18: note: declared here
        template <class T>
                        ^
../src/fibers.cc:83:36: error: use of undeclared identifier 'handle'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                          ^
../src/fibers.cc:83:48: error: expected '(' for function-style cast or type construction
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                  ~~~ ^
../src/fibers.cc:83:59: error: expected '(' for function-style cast or type construction
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                             ~~~~^
../src/fibers.cc:83:61: error: use of undeclared identifier 'val'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                                   ^
../src/fibers.cc:83:65: error: expected ';' at end of declaration
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                                       ^
                                                                       ;
../src/fibers.cc:83:66: error: expected unqualified-id
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
                                                                        ^
../src/fibers.cc:87:27: error: use of undeclared identifier 'Handle'
        void* GetInternalPointer(Handle<T> handle, int index) {
                                 ^
../src/fibers.cc:87:34: error: 'T' does not refer to a value
        void* GetInternalPointer(Handle<T> handle, int index) {
                                        ^
../src/fibers.cc:86:18: note: declared here
        template <class T>
                        ^
../src/fibers.cc:87:37: error: use of undeclared identifier 'handle'
        void* GetInternalPointer(Handle<T> handle, int index) {
                                           ^
../src/fibers.cc:87:49: error: expected '(' for function-style cast or type construction
        void* GetInternalPointer(Handle<T> handle, int index) {
                                                   ~~~ ^
../src/fibers.cc:87:55: error: expected ';' at end of declaration
        void* GetInternalPointer(Handle<T> handle, int index) {
                                                             ^
                                                             ;
../src/fibers.cc:87:56: error: expected unqualified-id
        void* GetInternalPointer(Handle<T> handle, int index) {
                                                              ^
../src/fibers.cc:92:2: error: no template named 'Handle'
        Handle<T> Deref(Isolate* isolate, Persistent<T>& handle) {
        ^
../src/fibers.cc:97:7: error: variable has incomplete type 'void'
        void Return(Handle<T> handle, const Arguments& args) {
             ^
../src/fibers.cc:97:14: error: use of undeclared identifier 'Handle'
        void Return(Handle<T> handle, const Arguments& args) {
                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lalit/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/lalit/.nvm/versions/node/v12.14.0/bin/node" "/Users/lalit/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd //mycode//node_modules/fibers
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN cucumber-pretty@1.5.2 requires a peer of cucumber@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN my-app@3.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lalit/.npm/_logs/2020-01-07T12_19_13_237Z-debug.log
`

**Comment by RoValentim** [comment]
I could install with `-g` option, so the issue is only for local directory I guess.

**Comment by charlierudolph** [comment]
For both sets of provided node and npm versions, I started in an empty folder ran `npm init` (to create a package.json file) and then `npm install cucumber` and the package was installed as expected.

Did run into what I find weird behavior where if you don't have a `package.json` file then the node module does not get saved locally on install (that is an npm issue though and not specific to cucumber).

I'm very confused by your case @RoValentim, what is in your cucumber directory? Maybe something there is causing the issue?

@tolalitnegi the error related to fiber is not specific to cucumber and I believe due to fiber being a dependency of some other package you have installed.

**Comment by RoValentim** [comment]
> For both sets of provided node and npm versions, I started in an empty folder ran `npm init` (to create a package.json file) and then `npm install cucumber` and the package was installed and usable.
> 
> Did run into what I find weird behavior where if you don't have a `package.json` file then the node module does not get saved locally on install (that is an npm issue though and not specific to cucumber).
> 
> I'm very confused by your case @RoValentim, what is in your cucumber directory? Maybe something there is causing the issue?
> 
> @tolalitnegi the error related to fiber is not caused by cucumber and I believe due to fiber being a dependency of some other package you have installed.

The directory doesn't matter because you're right about the need of `package.json`, with it the local directory installation worked.

Would be nice to have this information in `Install` part of README, because this weird situation is happening only for cucumber (at least for me), so I don't think this is related to `npm`, because I just did `npm install newman` without a package.json and worked, so `npm install` first is needed by cucumber only, maybe with this new version of `npm` something extra need to be done by cucumber to work properly.

I'm closing because there's this workaround doing `npm install` first.

**Comment by charlierudolph** [comment]
In an empty directory running `npm install newman` does not install it for me (no node_modules folder gets created). How are you verifying it gets installed? I'm using npm version 6.13.6 by the way

**Comment by davidvc** [comment]
I also get this error, even when I run npm install on a fresh pull of my git repo.  I'm using node v15.14.0 and npm 7.7.6

```
npm WARN deprecated cucumber@6.0.5: The npm package has moved to @cucumber/cucumber
npm ERR! code 1
npm ERR! path /home/circleci/project/test/node_modules/grpc
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/circleci/project/test/node_modules/grpc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/circleci/.cache/node-gyp/15.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/circleci/.cache/node-gyp/15.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/circleci/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/circleci/project/test/node_modules/grpc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.19.121-linuxkit
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/circleci/project/test/node_modules/grpc
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```
