### ISSUE TITLE
The "from" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by stefdelec** [cucumber/cucumber-js#1326]
I am trying to use steps I wrote and publish on npm
Here is the error I have:
```
> cucumber-js e2e/src/**/*.feature --require ./node_modules/@myProject/uat/dist/*.step.js

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received type undefined
at validateString (internal/validators.js:125:11)
at Object.relative (path.js:1162:5)
at getDefinitionLineAndUri (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:184:27)
at buildStepDefinitionConfig (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:124:7)
at SupportCodeLibraryBuilder.defineStep (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/node_modules/cucumber/lib/support_code_library_builder/index.js:51:79)
at Object.<anonymous> (/home/myname/Documents/myProject/mysubProjectV2/node_modules/@myProject/uat/dist/click.step.js:40:12)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at supportCodePaths.forEach.codePath (/home/myname/Documents/myProject/mysubProjectV2/node_modules/cucumber/lib/cli/index.js:142:42)
at Array.forEach (<anonymous>)
at Cli.getSupportCodeLibrary (/home/myname/Documents/myProject/mysubProjectV2/node_modules/cucumber/lib/cli/index.js:142:22)
```

I have found that this is ```this.cwd``` which is undefined. What can i do?
![image](https://user-images.githubusercontent.com/12082478/84280707-f29abe80-ab37-11ea-878e-9b96429fb321.png)

If I copy paste my steps in the root directory (where the package.json is), I don't have any error. So the problem is: I cannot not --require from node_modules.

**Comment by jonathanwork** [comment]
did you try from node_modules in your local directory ?

**Comment by VivekLande** [comment]
any resolution for this issue, I am getting this error with Cucumber 7

**Comment by davidjgoss** [comment]
@stefdelec @VivekLande this is likely related to either

- your steps package depending on a different version of cucumber than your host project
- working locally with your steps package `npm link`'d

In either case you can end up with two different cucumber-js instances at runtime which can cause this.

I'm working on documenting this in #1540 - take a look at [the workaround](https://github.com/cucumber/cucumber-js/blob/93fbb958432583ca5fab74a73041b05f3b2e8832/docs/faq.md#why-am-i-seeing-the-from-argument-must-be-of-type-string-received-type-undefined) and see if that works for you?

**Comment by VivekLande** [comment]
Thanks @davidjgoss, I am able to resolved the issue with the solution provided by you.

**Comment by csurfleet** [comment]
This workaround isn't working for me. I've definitely not got cucumber installed elsewhere. I've been on this for hours and I'm getting nowhere. This is my package json dependencies:
```
"dependencies": {
    "@cucumber/cucumber": "^7.0.0",
    "@cucumber/cucumber-expressions": "^12.0.0",
    "gherkin-testcafe": "^5.0.0",
    "testcafe": "^1.13.0"
  }
```

I've searched my node_modules folder and cucumber isn't in there multiple times. I've no idea where to go next

**Comment by charlierudolph** [comment]
@csurfleet can you please create a minimal reproducible example?

**Comment by phatNfqAsia** [comment]
In my case, 
Import a cucumber step-implementation module in a normal es module file (e.g `index.ts`) will lead to error: `TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined`
So the solution is to extract the logic and export normal functions from a different non-cucumber-related file

**Comment by phatNfqAsia** [comment]
@aurelien-reeves my repo is kept private so I can not share, sorry :(
My issue is when I am trying to call some API of `@cucumber/cucumber` with `ts-node` instead of `cucumber-js` command.
In fact I don't need to use it, the program throw error because I accidentally import one file that refer to that cucumber package. 
So I detach the logic inside the `to-import` file, make sure it does not contain any cucumber reference and then my code start working.

**Comment by aurelien-reeves** [comment]
Ok, thanks for the details.

When I asked for a repo, that could be a reproduction repo made simple without confidential data. As simple as possible to reproduce the issue

**Comment by vcardins** [comment]
Wondering why this issue was closed. Still happening

**Comment by aurelien-reeves** [comment]
As requested before, would you have a minimal reproducible example?
That would help us helping you with this issue

**Comment by VictorVermeulen** [comment]
> Wondering why this issue was closed. Still happening

https://github.com/cucumber/cucumber-js/blob/HEAD/docs/transpiling.md Did you try this?

**Comment by Shristy1901** [comment]
I am still facing this issue,. tried all the possible things to resolve the error like : work around this by using import-cwd so your support code always requires cucumber-js from the current working directory (i.e. host project):

const importCwd = require('import-cwd') const { Given, When, Then } = importCwd('@cucumber/cucumber').

Nothing works for me. Please help me with proper solution.
