### ISSUE TITLE
HTML formatter missing from 7.0.0-rc.0 ?

### ISSUE THREAD

**Issue by nickgrealy** [cucumber/cucumber-js#1507]
Hi,

Version: `"@cucumber/cucumber": "7.0.0-rc.0"` (_package.json_)

When attempting to run `cucumber-js --format html:html-formatter.html`, I get the following error:

```sh
Error: Cannot find module '/Users/myproject/html'
Require stack:
- /Users/myproject/node_modules/@cucumber/cucumber/lib/formatter/builder.js
- /Users/myproject/node_modules/@cucumber/cucumber/lib/cli/index.js
- /Users/myproject/node_modules/@cucumber/cucumber/lib/cli/run.js
- /Users/myproject/node_modules/@cucumber/cucumber/bin/cucumber-js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.loadCustomFormatter (/Users/myproject/node_modules/@cucumber/cucumber/lib/formatter/builder.js:74:33)
    at Object.getConstructorByType (/Users/myproject/node_modules/@cucumber/cucumber/lib/formatter/builder.js:55:41)
    at Object.build (/Users/myproject/node_modules/@cucumber/cucumber/lib/formatter/builder.js:23:55)
    at /Users/myproject/node_modules/@cucumber/cucumber/lib/cli/index.js:96:38
```

[Looking at the published source](https://unpkg.com/browse/@cucumber/cucumber@7.0.0-rc.0/lib/formatter/builder.js), there is no option for `html` in the switch statement - so it falls back to assuming `html` is a custom formatter. 

Here is the [merged PR for #1432](https://github.com/cucumber/cucumber-js/pull/1432/files#diff-b025e67992fe4919d6b10362df4591b247371d0c8413fd272b338c8d03e56613R68-R69)
... which is listed in the [`7.0.0-rc.0` release changelog](https://github.com/cucumber/cucumber-js/compare/v7.0.0-rc.0...master)
... but the change [isn't in the source for the released hash](https://github.com/cucumber/cucumber-js/blob/94b7f6ea9aa2141aa660a7e8dace7f5e8d9e1333/src/formatter/builder.ts#L60-L83)
... => Bad merge?

**Comment by nickgrealy** [comment]
It's not in the 7.0.0-rc.0 release... I jumped the gun. => [In since been committed...](https://github.com/cucumber/cucumber-js/compare/v7.0.0-rc.0...master)
