### ISSUE TITLE
Error when trying to publish reports: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function

### ISSUE THREAD

**Issue by Fryuni** [cucumber/cucumber-js#1521]
I got this error just by enabling `--publish`:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:111:11)
    at ClientRequest.once (events.js:435:3)
    at new ClientRequest (_http_client.js:202:10)
    at Object.request (https.js:313:10)
    at Object.request (/<my-project-root>/node_modules/agent-base/patch-core.js:25:22)
    at HttpStream.sendRequest (/<my-project-root>/node_modules/@cucumber/cucumber/src/formatter/http_stream.ts:106:25)
    at IncomingMessage.<anonymous> (/<my-project-root>/node_modules/@cucumber/cucumber/src/formatter/http_stream.ts:100:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Doesn't prevent me from working at all. I just wanted to try the new reports feature, using the `--publish-quiet` to remove the banner works fine.

Using version `7.0.0`

**Comment by davidjgoss** [comment]
Hi @Fryuni, are you still seeing this issue, and if so are you able to link to a repository where I can reproduce it?

I am able to publish reports successfully in [this small example project](https://github.com/davidjgoss/cucumber-puppeteer-typescript-starter) with:

```shell
npm i
npx cucumber-js --publish
```

**Comment by davidjgoss** [comment]
Closing as we've gone quiet here.
