### ISSUE TITLE
Running cucumber-js 7.0 test generates error "formatter.finished is not a function

### ISSUE THREAD

**Issue by VivekLande** [cucumber/cucumber-js#1544]
On The execution of scenarios, Cucumber 7 end with throwing below error
Series 1 then executed
Series 2 when executed
Series 2 then executed
fail when executed    
Series 1 when executed
Series 1 then executed
Series 2 when executed
Series 2 then executed
fail when executed
6 scenarios (6 passed)
10 steps (10 passed)
0m00.067s (executing steps: 0m00.049s)
[20:23:37] E/launcher - Error: TypeError: formatter.finished is not a function
    at C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\@cucumber\cucumber\src\cli\index.ts:138:25
    at tryCatcher (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\reduce.js:166:18)        
    at Object.gotAccum (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\reduce.js:155:25)        
    at Object.tryCatcher (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\promise.js:604:18)    at Promise._settlePromiseCtx (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\async.js:102:5)       
    at Immediate.Async.drainQueues (C:\Projects\Cucumber_7_Migration\cucumber_7_migration_sample\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
[20:23:37] E/launcher - Process exited with error code 100

![image](https://user-images.githubusercontent.com/16791810/104931288-3443ef80-59cc-11eb-9598-ebca372de058.png)

**Comment by davidjgoss** [comment]
Hey @VivekLande - do you have any custom formatters in your project? If so do they extend the built-in Formatter class?

**Comment by VivekLande** [comment]
Yes, I am using custom formatters but hadn't extended to a built-in class, post your comment, I tried the way and the issue solved.
Thanks. closing the issue.

**Comment by Bhudeb** [comment]
This issue needs to be reopened, as it is still there.
`npm run testcuke

> flexible-student-journey-automation@0.0.1 testcuke
> env-cmd -e stingrays ./node_modules/@cucumber/cucumber/bin/cucumber-js --require-module ts-node/register src/features/linearLesson.feature

TypeError: formatter.finished is not a function
    at /Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/@cucumber/cucumber/src/cli/index.ts:152:25
    at tryCatcher (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/bhudebsarkar/Automation/flexible-student-journey-automation/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)`



<img width="1235" alt="Screen Shot 2021-09-15 at 4 28 32 AM" src="https://user-images.githubusercontent.com/12228879/133344643-b3cfe081-d951-4a57-81ae-705f0d1eb957.png">

**Comment by aurelien-reeves** [comment]
Are you using custom formatters, or non built-in formatters not compatible with cucumber-js 7?

If you are using custom formatters, please consider upgrading those (make sure to extend the built-in `Formatter` class). If you are using other third-party formatters, make sure to use formatters compatible with cucumber-js 7

**Comment by Bhudeb** [comment]
looking into it and will get back to you.

**Comment by aurelien-reeves** [comment]
Would you have an example please? A minimal reproduction example would be great!

**Comment by antonmikolaevich** [comment]
hi @davidjgoss , @Bhudeb , @VivekLande , @aurelien-reeves , @mohitpubnub 
if you have a chance, could you please help to fix probably the same issue if you had a success with it:

TypeError: f.finished is not a function
    at D:\Automation Program Global - Advanced\Homework 2  - Test Automation Framework Design\homework-framework\node_modules\@cucumber\cucumber\lib\api\formatters.js:45:63
    at Array.map (<anonymous>)
    at D:\Automation Program Global - Advanced\Homework 2  - Test Automation Framework Design\homework-framework\node_modules\@cucumber\cucumber\lib\api\formatters.js:45:38
    at runCucumber (D:\Automation Program Global - Advanced\Homework 2  - Test Automation Framework Design\homework-framework\node_modules\@cucumber\cucumber\lib\api\run_cucumber.js:107:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Cli.run (D:\Automation Program Global - Advanced\Homework 2  - Test Automation Framework Design\homework-framework\node_modules\@cucumber\cucumber\lib\cli\index.js:50:29)
    at async Object.run [as default] (D:\Automation Program Global - Advanced\Homework 2  - Test Automation Framework Design\homework-framework\node_modules\@cucumber\cucumber\lib\cli\run.js:34:18)

**Comment by antonmikolaevich** [comment]
> Yes, I am using custom formatters but hadn't extended to a built-in class, post your comment, I tried the way and the issue solved. Thanks. closing the issue.

@VivekLande could you please help me how to fix the similar issue
what does "extend built-in Formatter class mean?

**Comment by VivekLande** [comment]
Hey @antonmikolaevich, Please check the **npm tree** that you don't have multiple versions of cucumber-js by any of the internal packages, that can cause this issue. Thanks
