### ISSUE TITLE
Cucumber.js 7 fails to generate snippets

### ISSUE THREAD

**Issue by cwansart** [cucumber/cucumber-js#1571]
Cucumber.js version 7 has an issue when generating the snippets. It fails with

```
TypeError: this.parameterTypes is not a function
    at CucumberExpressionGenerator.createParameterTypeMatchers (/home/runner/work/cucumber-js-test/cucumber-js-test/node_modules/@cucumber/cucumber-expressions/dist/src/CucumberExpressionGenerator.js:110:41)
    at CucumberExpressionGenerator.generateExpressions (/home/runner/work/cucumber-js-test/cucumber-js-test/node_modules/@cucumber/cucumber-expressions/dist/src/CucumberExpressionGenerator.js:27:42)
Error: Process completed with exit code 1.
```

It fails when a snippet is missing. In my example project I just used the [asd](https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md)

What I have found is this fix: https://github.com/cucumber/cucumber-expressions-javascript/commit/4c092a16b169e4e2d50b32112e60cb8d7241c7ef
I guess this could be the issue or there is something wrong with parsing the parameters?

My project currently uses:
 * @cucumber/cucumber: 7.0.0
 * @cucumber/cucumber-expressions: 11.0.1

**Comment by aslakhellesoy** [comment]
Hi - we've just released `cucumber-expressions` version `11.0.2` which fixes a regression from `11.0.1`. If you `npm update` the problem should go away.
