### ISSUE TITLE
Error in json_formatter

### ISSUE THREAD

**Issue by dmitriyKowWib** [cucumber/cucumber-js#1652]
Fails to create json report file after run:
47 scenarios (14 failed, 18 skipped, 15 passed)
347 steps (14 failed, 156 skipped, 177 passed)
3m15.454s (executing steps: 18m36.066s)

/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:185
                : scenarioSource.location.line;
                                 ^

TypeError: Cannot read property 'location' of undefined
    at lodash_1.default.map (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:185:34)
    at arrayMap (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:653:23)
    at Function.map (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:9622:14)
    at JsonFormatter.getScenarioTags (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:180:33)
    at JsonFormatter.getScenarioData (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:125:24)
    at group.map (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:84:29)
    at Array.map (<anonymous>)
    at lodash_1.default.map (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:69:36)
    at /home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:3585:27
    at /home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:3032:24)
    at /home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:4936:18
    at baseMap (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js:9622:14)
    at JsonFormatter.onTestRunFinished (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:63:43)
    at EventEmitter.JsonFormatter.options.eventBroadcaster.on (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:23:22)
    at EventEmitter.emit (events.js:187:15)
    at Coordinator.onWorkerProcessClose (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/runtime/parallel/coordinator.js:109:35)
    at ChildProcess.worker.process.on (/home/jenkins/apiAutomation/node_modules/@cucumber/cucumber/lib/runtime/parallel/coordinator.js:92:18)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by aslakhellesoy** [comment]
What Cucumber version @dmitriyKowWib?

**Comment by aslakhellesoy** [comment]
Please provide an example that lets us reproduce this.

**Comment by davidjgoss** [comment]
Closing as we don't have enough info to reproduce.
