### ISSUE TITLE
Including the word "reissue" in a tag name breaks tests

### ISSUE THREAD

**Issue by sarahgoldman** [cucumber/cucumber-js#1707]
**Describe the bug**

If I tag a scenario with "@reissue" or even a tag name containing that word, e.g. "@reissueassignment", the tests fail with error:

```
[12:25:46] E/launcher - Error: Error: Tag name should have a property "length" that is greater than 0
    at Object.ensure (C:\jdev2020\git\via-automated-testing\node_modules\tiny-types\src\ensure.ts:31:15)
    at new Tag (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\core\src\model\tags\Tag.ts:23:9)
    at new IssueTag (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\core\src\model\tags\IssueTag.ts:10:9)
    at C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\core\src\model\tags\Tags.ts:17:66
    at Array.map (<anonymous>)
    at MatchesRegExp.transformation (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\core\src\model\tags\Tags.ts:17:53)
    at MatchesRegExp.MatcherRule.execute (C:\jdev2020\git\via-automated-testing\node_modules\tiny-types\src\pattern-matching\rules\MatcherRule.ts:13:21)
    at StringMatcher.PatternMatcher.else (C:\jdev2020\git\via-automated-testing\node_modules\tiny-types\src\pattern-matching\PatternMatcher.ts:17:71)
    at Function.from (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\core\src\model\tags\Tags.ts:18:18)
    at C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\cucumber\src\listeners\messages\parser\CucumberMessagesParser.ts:233:80
    at Array.map (<anonymous>)
    at CucumberMessagesParser.scenarioFrom (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\cucumber\src\listeners\messages\parser\CucumberMessagesParser.ts:233:64)
    at CucumberMessagesParser.parseTestCaseStarted (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\cucumber\src\listeners\messages\parser\CucumberMessagesParser.ts:102:34)
    at EventEmitter.<anonymous> (C:\jdev2020\git\via-automated-testing\node_modules\@serenity-js\cucumber\src\listeners\messages\CucumberMessagesListener.ts:49:41)
    at EventEmitter.emit (events.js:323:22)
    at EventEmitter.emit (domain.js:482:12)
[12:25:46] E/launcher - Process exited with error code 100
```

**To Reproduce**
Tag a scenario with "@reissue" or "@reissuesomething". 

**Note**: I am using with protractor-cucumber-framework@~8.0.0

Here is my feature file:
```
@VIA-150 @establishment @establishmentdetails
Feature: VIA-150 CREATE ASSIGNMENTS
    All functionality related to creating an assignments
    
    @reissue
    Scenario: 150-16449-AC1-HP2
        Given "Coordinator" user is logged in
        And the user is viewing an establishment that is marked to be reissued an assignment
        When the user creates an assignment for the establishment
        Then the system shall display the "Establishment Detail" screen
        And the establishment shall not display the Reissue badge
```

When I change it to "reissu" without the "e", it works as expected:

```
@VIA-150 @establishment @establishmentdetails
Feature: VIA-150 CREATE ASSIGNMENTS
    All functionality related to creating an assignments
    
    @reissu
    Scenario: 150-16449-AC1-HP2
        Given "Coordinator" user is logged in
        And the user is viewing an establishment that is marked to be reissued an assignment
        When the user creates an assignment for the establishment
        Then the system shall display the "Establishment Detail" screen
        And the establishment shall not display the Reissue badge
```

**Is @reissue a reserved word and is this documented somewhere, or is this a bug?**

**Comment by davidjgoss** [comment]
Hi @sarahgoldman, thanks for raising - this was an odd one. I can confirm there are no reserved words for tags in Cucumber itself.

The stack trace you included was helpful though, leading to [this code in serenity-js](https://github.com/serenity-js/serenity-js/blob/master/packages/core/src/model/tags/Tags.ts#L17) which is doing special handling for tags that include "issue" or "issues". There's [some documentation here](https://serenity-js.org/handbook/integration/jira-and-other-issue-trackers.html) which explains what this is about.

It doesn't seem like there's a way to opt out of this behaviour, but it might be worth raising an issue in that repo?

**Comment by sarahgoldman** [comment]
Ah that makes sense! I have opened an issue on the Serenity/JS repo here: https://github.com/serenity-js/serenity-js/issues/894

Thanks for the insight.

**Comment by davidjgoss** [comment]
No problem!
