### ISSUE TITLE
Cannot use cucumber.js file with esm

### ISSUE THREAD

**Issue by TheLudd** [cucumber/cucumber-js#1823]
**Describe the bug**
When using a cucumber.js file, cucumber fails if running with esm. Says it cannot use `require` to load the file

**To Reproduce**
1. Use version 8.0.0-rc1
2. Add a `cucumber.js` file to the root of your package.
3. Set `type: module` in your `package.json`
3. Run cucumber with steps written in esm format

**Expected behavior**
`cucumber.js` should be able to use esm code and otherwise work as before.

**Actual result**

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/cucumber8/cucumber.js
require() of ES modules is not supported.
require() of /tmp/cucumber8/cucumber.js from /tmp/cucumber8/node_modules/@cucumber/cucumber/lib/cli/profile_loader.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename cucumber.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/cucumber8/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at ProfileLoader.loadFile (/tmp/cucumber8/node_modules/@cucumber/cucumber/lib/cli/profile_loader.js:28:29)
    at ProfileLoader.getDefinitions (/tmp/cucumber8/node_modules/@cucumber/cucumber/lib/cli/profile_loader.js:21:25)
    at ProfileLoader.getArgv (/tmp/cucumber8/node_modules/@cucumber/cucumber/lib/cli/profile_loader.js:35:40)
    at Object.getExpandedArgv (/tmp/cucumber8/node_modules/@cucumber/cucumber/lib/cli/helpers.js:37:65)
```

Besides that, thanks for pushing this release.

**Comment by davidjgoss** [comment]
Hey @TheLudd, that config file has some unresolved issues with ESM, best thing right now is to rename to .cjs and use CommonJS syntax which should work - let me know.

**Comment by garfieldnate** [comment]
For the next googler: note that ESM modules do *not* work when using TypeScript or another transpiler (as documented).

**Comment by Pyrolistical** [comment]
ESM has been considered stable since node.js 12.x https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_enabling

This project requires at least node 12: https://github.com/cucumber/cucumber-js/blob/main/package.json#L190-L192

Something to consider would be to do what jest does regarding esm support https://jestjs.io/docs/ecmascript-modules

**Comment by davidjgoss** [comment]
@Pyrolistical see https://github.com/cucumber/cucumber-js/blob/main/docs/esm.md for the current status on ESM.
