### ISSUE TITLE
Cannot use the HTML formater in 8.2.0

### ISSUE THREAD

**Issue by sl-nigelalmada** [cucumber/cucumber-js#2039]
### 👓 What did you see?

When attempting to run `cucumber-js -p default --retry 3 --format json:cucumber/tests.cucumber --format html:cucumber-report.html`, I get the following error:

```
Error: Cannot find module '/project-folder/html'
Require stack:
- /project-folder/node_modules/cucumber/lib/formatter/builder.js
- /project-folder/node_modules/cucumber/lib/cli/index.js
- /project-folder/node_modules/cucumber/lib/cli/run.js
- /project-folder/node_modules/cucumber/bin/cucumber-js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/project-folder/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Function.loadCustomFormatter (/project-folder/node_modules/cucumber/lib/formatter/builder.js:110:29)
    at Function.getConstructorByType (/project-folder/node_modules/cucumber/lib/formatter/builder.js:77:33)
    at Function.build (/project-folder/node_modules/cucumber/lib/formatter/builder.js:38:40)
    at /project-folder/node_modules/cucumber/lib/cli/index.js:104:31
```

Nothing seems to be missing in my implementation and my test are perfectly running if I remove the `--format html:cucumber-report.html` option

### 📦 Which tool/library version are you using?

Version: `@cucumber/cucumber: "8.2.0"`
Extract from `packages.json` : 
```
"cucumber": "^6.0.7",
"@cucumber/cucumber": "8.2.0",
"cucumber-pretty": "^6.0.1",
"cucumber-tsflow": "^3.4.1",
```

TIA

**Comment by davidjgoss** [comment]
Hey @sl-nigelalmada, it looks like you have the [old `cucumber` package](https://www.npmjs.com/package/cucumber) installed there, and from the stack trace that's what's being executed.

You'll need to remove that (and possibly do a fresh `npm install`) so the `cucumber-js` executable will point to the right package i.e. `@cucumber/cucumber`.
