### ISSUE TITLE
Failed tests exit with exit code 0

### ISSUE THREAD

**Issue by MaxTeiger** [cucumber/cucumber-js#2116]
### 👓 What did you see?

It is kind of the same problem as in this issue : https://github.com/cucumber/cucumber-js/issues/231
I ran cucumberjs inside circleci, my tests fail but as the process exits with exit code 0, the CI considers it as "Ok"

### ✅ What did you expect to see?

Have an exit code 1 instead of exit code 0 when any test is failing. 

### 📦 Which tool/library version are you using?

```json
@cucumber/cucumber": "7.2.x",
```

### 🔬 How could we reproduce it?

Run cucumber-js in the CI with the following parameters :
```bash
npx cucumber-js --require [...] --require [...] -f @cucumber/pretty-formatter [...] --retry 2 --fail-fast --tags [...] --retry 1
```

Note : I also tried without the retry flag, didn't work

**Comment by charlierudolph** [comment]
Hi @MaxTeiger, we have a number of feature tests that verify the exit code is non-zero. Can you please give more detail on the version of cucumber-js used? For this, I think may also be good to try to setup a minimal repo that can be used to reproduce the issue.

**Comment by MaxTeiger** [comment]
Hello @charlierudolph ! Thank you for your quick response. I am pretty new to cucumberjs, and I am working on an existing repository, so do not hesitate if my response is not accurate. 

For more information : 

I use [Arianee UAT](https://www.npmjs.com/package/@arianee/uat) which uses cucumber `7.2.1` 
```bash
npm list @cucumber/cucumber
xxx
└─┬ @arianee/uat@2.47.0
  └── @cucumber/cucumber@7.2.1
```

But the command run at the end is : 
```bash
npx cucumber-js --require "project/node_modules/@arianee/uat/common_steps/*.step.js" --require "project/custom_steps/*.step.js" -f @cucumber/pretty-formatter ./features/Event.feature ./features/api.automessage.feature ./features/api.certificate.feature ./features/api.demo.feature ./features/api.identity.feature ./features/api.report.feature ./features/api.search.feature ./features/api.wallet.feature ./features/api.walletHistory.feature ./features/asynchronous_transfer.feature ./features/buyCredits.feature ./features/certificateCreationV2.feature ./features/certificateMultipleDuplication.feature ./features/destroyCertificate.feature ./features/identity.feature ./features/login.feature ./features/users.feature --retry 2 --fail-fast --tags @api --retry 1
```

Here is the (shortened) output I have : 
```bash
@api
Feature: User can call api # features/api.Event.feature:2

  @api
  Scenario: user can create event via API # features/api.Event.feature:7
browser chromium
    Given _store value from process.env.BDHAPIURL as '{{APIURL}}'
    Given _api user can 'create Event' with api call:
      │ url       │ {{APIURL}}/api/createEvent │
      │ x-api-key │ user-1-admin-api-key              │
      │ method    │ POST                              │
    And _api body of 'create Event' is:
      """
       [
        {
            "certificateId": xxx,
            "content": {
              "$schema": "https://cert.xxx.org/version1/Event-i18n.json",
              "title": "A title"
          }
        }
             ]
      """
    When _api user make call 'create Event'
    ✖ failed
      FetchError: request to http://localhost:8080/api/createEvent failed, reason: connect ECONNREFUSED 127.0.0.1:8080
          at ClientRequest.<anonymous> (/root/project/node_modules/node-fetch/lib/index.js:1461:11)
          at ClientRequest.emit (events.js:315:20)
          at Socket.socketErrorListener (_http_client.js:469:9)
          at Socket.emit (events.js:315:20)
          at emitErrorNT (internal/streams/destroy.js:106:8)
          at emitErrorCloseNT (internal/streams/destroy.js:74:3)
          at processTicksAndRejections (internal/process/task_queues.js:80:21)
    Then _api result status of 'create Event' should be:
      │ status │ 200 │
    - skipped
check screenshot failed_step.png

  @api
  Scenario: user can create event via API # features/api.Event.feature:7
browser chromium
    Given _store value from process.env.BDHAPIURL as '{{APIURL}}'
    Given _api user can 'create Event' with api call:
      │ url       │ {{APIURL}}/api/createEvent │
      │ x-api-key │ user-1-admin-api-key              │
      │ method    │ POST                              │
    And _api body of 'create Event' is:
      """
       [
        {
            "certificateId": 377850379,
            "content": {
              "$schema": "https://cert.xxx.org/version1/Event-i18n.json",
              "title": "A title"
          }
        }
             ]
      """
    When _api user make call 'create Event'
    ✖ failed
      FetchError: request to http://localhost:8080/api/createEvent failed, reason: connect ECONNREFUSED 127.0.0.1:8080
          at ClientRequest.<anonymous> (/root/project/node_modules/node-fetch/lib/index.js:1461:11)
          at ClientRequest.emit (events.js:315:20)
          at Socket.socketErrorListener (_http_client.js:469:9)
          at Socket.emit (events.js:315:20)
          at emitErrorNT (internal/streams/destroy.js:106:8)
          at emitErrorCloseNT (internal/streams/destroy.js:74:3)
          at processTicksAndRejections (internal/process/task_queues.js:80:21)
    Then _api result status of 'create Event' should be:
      │ status │ 200 │
    - skipped
check screenshot failed_step.png
```

All following tests are skipped as expected, but the return exit code is 0. I use cucumber the same way in another repo and the exit code is 1 when a test fail like this. Did I make a configuration mistake ?

**Comment by MaxTeiger** [comment]
Hello @davidjgoss ! I just saw you flagged the issue as `incomplete`. Which information do you miss ?
I'll be happy to give it to you 😄

**Comment by davidjgoss** [comment]
Sorry for the late reply @MaxTeiger.

I did a little testing with the `@arianee/uat`, and even the simplest failing test still yields a 0 exit code. But also, in either success or failure cases, you can see cucumber-js doesn't finish executing as the final summary output doesn't appear in the console. I proved this by wrapping the invocation of cucumber-js in their bin script with a try/catch; it was never hit.

So this has to be something internal to the `@arianee/uat`, maybe one of their hooks or steps, that is causing the process to abruptly exit with code 0 before the test run has finished. You'll need to raise this with whoever maintains that project.
