### ISSUE TITLE
Strange error when execute parallel

### ISSUE THREAD

**Issue by tkminh** [cucumber/cucumber-js#2161]
Hello guys,

I have some features file and cucumber-js has been configed as following
const ci = {
  requireModule: ["ts-node/register"],
  require: [
    "src/core/**/*.ts",
    "src/page/**/*.ts",
    "src/step-definitions/**/*.ts",
    "src/shared/**/*.ts",
  ],
  worldParameters: {
    client: 'varsam'
  },
  **parallel: 3,**
  retry: 0,
  format: [
    "@cucumber/pretty-formatter",
    "json:reports/test_report.json",
    "progress-bar",
  ],
  monochrome: true,
};
module.exports = {
  default: ci,
};

### 👓 What did you see?
It already launch 3 workers, but show error in Give / When / Then like this:
TypeError: Cannot read properties of null (reading 'map')
    at StepDefinition.getInvocationParameters (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\models\step_definition.ts:30:39)
    at Object.run (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:34:43)
    at TestCaseRunner.invokeStep (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:130:29)
    at TestCaseRunner.runStep (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:312:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:214:36
    at async TestCaseRunner.aroundTestStep (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:162:28)
    at async TestCaseRunner.run (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:192:9)
    at async Worker.runTestCase (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:143:5)
    at async Worker.receiveMessage (C:\Users\terry.truong\Documents\testautofw\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:117:7)

### ✅ What did you expect to see?

These job should run on my local machine parallel 

### 📦 Which tool/library version are you using?

Typescript 

![error_cucumber](https://user-images.githubusercontent.com/1773192/197934801-ab223475-5258-484e-83b3-f0b739e91a9b.png)

**Comment by davidjgoss** [comment]
Does it work normally without parallel?

Can you post your code for the step that is erroring?

**Comment by tkminh** [comment]
Yes, it works normally without parallel.

The code is very simple for step "Give User like to test", just console.log("say test");

**Comment by davidjgoss** [comment]
Could you post a minimal reproducible example as a git repo?

**Comment by davidjgoss** [comment]
This should be fixed in https://github.com/cucumber/cucumber-js/releases/tag/v8.9.1
