### ISSUE TITLE
Help: Property 'user' does not exist on type 'Request<ParamsDictionary>'

### ISSUE THREAD

**Issue by raykahn65** [cucumber/cucumber-js#2176]
### 👓 What did you see?

When running a single cucumber test a TSError is thrown. However when command `npm run build` is executed or when the application is running no such error is thrown. Not sure whether this a version issue or something else. Below is the stacktrace of the error:

> npx node node_modules/.bin/cucumber-js --require 'features/support/**/*.ts' --require 'features/step_definitions/**/*.ts' --require-module ts-node/register --exit
TSError: ⨯ Unable to compile TypeScript:
src/activityFeed/activityFeedController.ts:25:54 - error TS2339: Property 'user' does not exist on type 'Request<ParamsDictionary>'.

25         return await service.getActivityFeed(request.user.userId, queryParams);
                                                        ~~~~

    at createTSError (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/raykahn/myprojects/owner-api/tsoa-build/routes.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module.m._compile (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/raykahn/myprojects/owner-api/node_modules/ts-node/src/index.ts:1621:12)

### ✅ What did you expect to see?

<!-- Describe what you would like to have happened instead. -->
A `/up` api call test is made and returns a 200 http response code

### 📦 Which tool/library version are you using?

<!-- What version of Cucumber/GoDog/etc. are you running? What version of your programming language platform? Anything else that might be relevant? -->
`node: v16.4.2`
`tsoa: ^4.1.0`
`@cucumber/cucumber: ^8.7.0`

> npm list typescript
owner-api@1.16.2 /Users/raykahn/myprojects/owner-api
├─┬ @typescript-eslint/eslint-plugin@4.33.0
│ └─┬ tsutils@3.21.0
│   └── typescript@4.8.4 deduped
├─┬ avail-policy-engine@3.0.2
│ └── typescript@4.8.4 deduped
├─┬ ts-jest@29.0.3
│ └── typescript@4.8.4 deduped
├─┬ ts-node@10.9.1
│ └── typescript@4.8.4 deduped
├─┬ tsoa@4.1.3
│ └─┬ @tsoa/cli@4.1.3
│   └── typescript@4.7.4
└── typescript@4.8.4

>  npm list cucumber  
owner-api@1.16.2 /Users/raykahn/myprojects/owner-api
└── cucumber@6.0.7


### 🔬 How could we reproduce it?

<!-- 
It order to fix the problem, we need to be able to reproduce it.

A Minimal Reproducible Example can be really helpful for anyone
trying to diagnose and fix the problem.

See https://stackoverflow.com/help/minimal-reproducible-example

Please outline the steps below:
-->

Steps to reproduce the behavior:
1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

<!-- you can add screenshots if that would be useful -->

### 📚 Any additional context?

<!-- Add any other context, references or screenshots about the problem here. -->
This is a simple and small test; nothing fancy!
----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
This is a compilation error in your code that doesn't relate to any Cucumber types. It's hard to know what it might be without tons of detail about your project, but a couple of things you might look at:

- It looks like you might have both `@cucumber/cucumber` (current) and `cucumber` (legacy) npm packages installed?
- [ts-node](https://www.npmjs.com/package/ts-node#configuration) will pick up the `tsconfig.json` from your working dir automatically - could this be different to what you're using in other contexts where there's no error?
