### ISSUE TITLE
providing configuration in cucumber.json is not running test scenarios

### ISSUE THREAD

**Issue by mrsenzy** [cucumber/cucumber-js#2180]
### ✅ What did you expect to see?

Provided configuration in cucumber.json to run scenarios using cucumber-js run command  and getting below error. while providing same configuration through cucumber.js and running through test command, it trigger test and works fine. Expecting same to work through cucumber.json as well.

Feature: Verify API Testing in application
                ^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .js] (C:\CodeNew\playwright\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at C:\CodeNew\playwright\node_modules\@cucumber\cucumber\src\api\support.ts:24:30
    at Array.map (<anonymous>)
### 🔬 How could we reproduce it?

cucumber.json:

{
	"default": {
		"require": [
			".\\tests-examples\\features\\*.feature",
			".\\tests-examples\\stepDefinitions\\**\\*.ts",
			".\\cucumber.config.ts"
		],
		"requireModule": [
			"ts-node/register"
		],
		"format": [
			"html:.\\report\\cucumberjs-report.html",
			"progress-bar",
			".\\node_modules\\@cucumber\\pretty-formatter",
			"json:.\\report\\report.json"
		],
		"publishQuiet": true
	}
}

run cucumber-js 

1. Install '...' version '...'  1.27.1
2. Create a file called '....' cucumber.json
3. Run command '....' cucumber-js
4. See error '....' 
Feature: Verify API Testing in application
                ^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .js] (C:\CodeNew\playwright\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at C:\CodeNew\playwright\node_modules\@cucumber\cucumber\src\api\support.ts:24:30
    at Array.map (<anonymous>)

![image](https://user-images.githubusercontent.com/75691269/203643890-18c6bfd3-d64b-4a4b-8d9a-deb786711fad.png)

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by davidjgoss** [comment]
That error is Node.js trying to parse your feature file and failing because it’s expecting JavaScript.

Your feature paths should not go in the “require” array, but in “paths”. Other than that your config looks fine.

**Comment by mrsenzy** [comment]
Thanks much David. This helps.
