### ISSUE TITLE
Cannot find module './cucumber.js' code: MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by devexpert7** [cucumber/cucumber-js#2313]
### 👓 What did you see?

cucumber
ts-node node-modules/@cucumber/cucumber/bin/cucumber.js -p default features --name say-hello
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './cucumber.js'
Require stack:
- /Users/project/node-modules/@cucumber/cucumber/bin/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:127:19)
    at requireResolveNonCached (/Users/project/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/Users/project/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/Users/project/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/Users/project/node_modules/ts-node/dist/bin.js:47:30)
    at main (/Users/project/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/project/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/project/node-modules/@cucumber/cucumber/bin/imaginaryUncacheableRequireResolveScript'
  ]
}

### ✅ What did you expect to see?

Able to run cucumber scenario 

### 📦 Which tool/library version are you using?

Cucumberjs ^9.3.0
Typescript 5.1.6
Node 18

### 🔬 How could we reproduce it?

1. Install Cucumber 
2.  "@cucumber/cucumber": "^9.3.0",
    "chromedriver": "^115.0.1",
    "cucumber": "^6.0.7",
    "source-map-loader": "^4.0.1",
    "ts-node": "^10.9.1"

3. Create a file called support.ts 
 import assert from "assert"
import { When, Then } from "cucumber"
import Greeter from "../src/index"

When('the greeter says hello', function () {
    // Write code here that turns the phrase above into concrete actions
    return 'pending';
  });

When("the greeter says hello1", function() {
    console.log("hurrayy");
    this.whatIHerad = new Greeter().sayHello()
})

Then("I should have heard {string}", function(expectedResponse) {
    assert.equal(this.whatIHerad, expectedResponse)
})

and also create file greeting.feature
Feature: Greeting

Scenario: say-hello
    When the greeter says hello
    Then I should have heard "hello"
5. Run command 'npm run cucumber -- features say-hello
6. See error '....'
Error: Cannot find module './cucumber.js'
Require stack:
- /Users/node-modules/@cucumber/cucumber/bin/imaginaryUncacheableRequireResolveScript
- 

### 📚 Any additional context?

0

I have node 18.17.1 and npm 9.6.7 on my machine.

I am trying to run the cucumber scenario and getting a module not found error when I try to execute the cucumber scenario. I tried npm install multiple times but was not able to get rid of this error.

terminal % npm run cucumber -- features --name say-hello

Below is package.json

{
  "type": "module",
  "files": [
    "src",
    "cucumber.js"
  ],
  "scripts": {
    "cucumber": "ts-node node-modules/@cucumber/cucumber/bin/cucumber.js -p default"
  },
  "dependencies": {
    "@cucumber/cucumber": "^9.0.1",
    "chromedriver": "^115.0.1",
    "cucumber": "^6.0.7",
    "ts-node": "^10.9.1",
    "typescript": "5.1.6"
  }
}
I tried different cucumber versions and npm install multiple times and also tried clean cache.
I was expecting this error is not thrown and execution is successful but getting this error every time.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by devexpert7** [comment]
This was resolved using typescript/esm loader.
