### ISSUE TITLE
Facing Issue with Parallelism in Jenkins while running Playwright Cucumber tests

### ISSUE THREAD

**Issue by onFilm** [cucumber/cucumber-js#2411]
### 👓 What did you see?

I've encountered an issue while attempting to run Playwright Cucumber tests in parallel on Jenkins. Locally, specifying parallel: 4 in cucumber.mjs works as expected on Windows. However, when running the tests on Jenkins, it seems to be executing in a single worker instead of utilizing parallelism.

### ✅ What did you expect to see?

Tests should run in parallel, leveraging the specified number of workers.

**Comment by onFilm** [comment]
With DEBUG=cucumber I see below
```
+ docker run --rm --entrypoint sh -e BUILD_NUMBER -e BUILD_URL -e JOB_NAME -e ENV=stable -e DEBUG=cucumber -v /var/lib/jenkins/workspace/testParallelExecution/reports:/tests/reports -w /tests testparallelexecution -c 'npx cucumber-js --tags "@Smoke" --parallel 4'
Configuration will be loaded from "cucumber.mjs"
No profiles specified; using default profile
Resolved configuration: {
  backtrace: false,
  dryRun: false,
  forceExit: false,
  failFast: false,
  format: [
    'json:reports/cucumber-report.json',
    'html:reports/report.html',
    'rerun:reports/@failedrerun.txt',
    '@cucumber/pretty-formatter'
  ],
  formatOptions: { snippetInterface: 'async-await', printAttachments: false },
  import: [],
  language: 'en',
  name: [],
  order: 'defined',
  paths: [],
  parallel: 4,
  publish: false,
  publishQuiet: true,
  require: [ 'step-definitions/*.ts', 'setup/*.ts', 'utils/*.ts' ],
  requireModule: [ 'ts-node/register' ],
  retry: 1,
  retryTagFilter: '@flaky',
  strict: true,
  tags: '(@Smoke)',
  worldParameters: { foo: 'bar' }
}
```

During execution, I encounter the error below in jenkins, but I don't observe it in my local run, also despite specifying parallel 4, resulting in at least 2 instances of Chrome launching in local.
```

VError: Unexpected error on worker.receiveMessage: a BeforeAll hook errored on worker 0, process exiting: setup/common-hooks.ts:19: function timed out, ensure the promise resolves within 60000 milliseconds
    at exit (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/run_worker.ts:8:38)
    at /tests/node_modules/@cucumber/cucumber/src/runtime/parallel/run_worker.ts:22:9
caused by: VError: a BeforeAll hook errored on worker 0, process exiting: setup/common-hooks.ts:19: function timed out, ensure the promise resolves within 60000 milliseconds
    at Worker.runTestRunHooks (/tests/node_modules/@cucumber/cucumber/src/runtime/run_test_run_hooks.ts:32:19)
    at Worker.initialize (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/worker.ts:93:5)
    at Worker.receiveMessage (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/worker.ts:110:7)
caused by: Error: function timed out, ensure the promise resolves within 60000 milliseconds
    at Timeout.<anonymous> (/tests/node_modules/@cucumber/cucumber/src/time.ts:52:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
VError: Unexpected error on worker.receiveMessage: a BeforeAll hook errored on worker 1, process exiting: setup/common-hooks.ts:19: function timed out, ensure the promise resolves within 60000 milliseconds
    at exit (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/run_worker.ts:8:38)
    at /tests/node_modules/@cucumber/cucumber/src/runtime/parallel/run_worker.ts:22:9
caused by: VError: a BeforeAll hook errored on worker 1, process exiting: setup/common-hooks.ts:19: function timed out, ensure the promise resolves within 60000 milliseconds
    at Worker.runTestRunHooks (/tests/node_modules/@cucumber/cucumber/src/runtime/run_test_run_hooks.ts:32:19)
    at Worker.initialize (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/worker.ts:93:5)
    at Worker.receiveMessage (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/worker.ts:110:7)
caused by: Error: function timed out, ensure the promise resolves within 60000 milliseconds
    at Timeout.<anonymous> (/tests/node_modules/@cucumber/cucumber/src/time.ts:52:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by onFilm** [comment]
I have BeforeAll as below, and still getting this error, I am not able to figure out what is causing. Can you help me figure out issue and solution, Thanks
![image](https://github.com/cucumber/cucumber-js/assets/26830666/951b9369-eadf-47be-986b-4efae8f20454)

` VError: Unexpected error on worker.receiveMessage: a BeforeAll hook errored on worker 1, process exiting: setup/common-hooks.ts:19: browserType.launch: Timeout 180000ms exceeded.
Call log:
  <launching> /ms-playwright/chromium-1124/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-gpu --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --window-size=1920,1080 --start-maximized --enable-automation --disable-extensions --no-sandbox --incognito --disable-dev-shm-usage --disable-infobars --disable-browser-side-navigation --whitelisted-ips --disable-gpu --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --remote-debugging-port=9222 --user-data-dir=/tmp/playwright_chromiumdev_profile-XXXXXXHeI3oy --remote-debugging-pipe --no-startup-window
  <launched> pid=53
  [pid=53][err] [0626/070635.107206:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
  [pid=53][err] [0626/070635.109662:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
  [pid=53][err] [0626/070635.109762:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
  [pid=53][err] [0626/070635.170152:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
  [pid=53][err] [0626/070635.217253:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
  [pid=53][err] [0626/070635.220922:ERROR:socket_posix.cc(147)] bind() failed: Address already in use (98)
  [pid=53][err] [0626/070635.221002:ERROR:socket_posix.cc(147)] bind() failed: Cannot assign requested address (99)
  [pid=53][err] [0626/070635.221027:ERROR:devtools_http_handler.cc(319)] Cannot start http server for devtools.
  at exit (/tests/node_modules/@cucumber/cucumber/src/runtime/parallel/run_worker.ts:8:38)
  at /tests/node_modules/@cucumber/cucumber/src/runtime/parallel/run_worker.ts:22:9
caused by: VError: a BeforeAll hook errored on worker 1, process exiting: setup/common-hooks.ts:19: browserType.launch: Timeout 180000ms exceeded. `

**Comment by mrsenzy** [comment]
@davidjgoss - Similar / Same issue occurring for me, but different stacktrace based on my custom playwright project with cucumber 10.8.0. we were using 10.3.1 and it was working fine and with 10.8.0 upgrade, it works fine for single thread execution but when parallel count is set to 1 or greater -- we get below error 

Error: Unexpected error on worker.receiveMessage
    at exit (C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\run_worker.ts:7:21)
    at C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\run_worker.ts:21:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: Cannot find module './stepDefinitions/**/*.ts'
  Require stack:
  - C:\Code\node_modules\@cucumber\cucumber\lib\try_require.js
  - C:\Code\node_modules\@cucumber\cucumber\lib\runtime\parallel\worker.js
  - C:\Code\node_modules\@cucumber\cucumber\lib\runtime\parallel\run_worker.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
      at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Code\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
      at Function.Module._load (node:internal/modules/cjs/loader:975:27)
      at Module.require (node:internal/modules/cjs/loader:1225:19)
      at require (node:internal/modules/helpers:177:18)
      at tryRequire (C:\Code\node_modules\@cucumber\cucumber\src\try_require.ts:9:12)
      at C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:72:67
      at Array.map (<anonymous>)
      at Worker.initialize (C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:72:41)
      at Worker.receiveMessage (C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:107:18) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Code\\node_modules\\@cucumber\\cucumber\\lib\\try_require.js',
      'C:\\Code\\node_modules\\@cucumber\\cucumber\\lib\\runtime\\parallel\\worker.js',
      'C:\\Codee\\node_modules\\@cucumber\\cucumber\\lib\\runtime\\parallel\\run_worker.js'
    ]
  }
}
Error: Unexpected error on worker.receiveMessage
    at exit (C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\run_worker.ts:7:21)
    at C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\run_worker.ts:21:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: Cannot find module './stepDefinitions/**/*.ts'
  Require stack:
  - C:\Code\node_modules\@cucumber\cucumber\lib\try_require.js
  - C:\Code\node_modules\@cucumber\cucumber\lib\runtime\parallel\worker.js
  - C:\Code\node_modules\@cucumber\cucumber\lib\runtime\parallel\run_worker.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
      at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Code\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
      at Function.Module._load (node:internal/modules/cjs/loader:975:27)
      at Module.require (node:internal/modules/cjs/loader:1225:19)
      at require (node:internal/modules/helpers:177:18)
      at tryRequire (C:\Code\node_modules\@cucumber\cucumber\src\try_require.ts:9:12)
      at C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:72:67
      at Array.map (<anonymous>)
      at Worker.initialize (C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:72:41)
      at Worker.receiveMessage (C:\Code\node_modules\@cucumber\cucumber\src\runtime\parallel\worker.ts:107:18) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Code\\node_modules\\@cucumber\\cucumber\\lib\\try_require.js',
      'C:\\Code\\node_modules\\@cucumber\\cucumber\\lib\\runtime\\parallel\\worker.js',
      'C:\\Code\\node_modules\\@cucumber\\cucumber\\lib\\runtime\\parallel\\run_worker.js'
    ]
  }
}

**Comment by onFilm** [comment]
@davidjgoss Thanks a lot for pointing out the port issue with Playwright. I appreciate your help and will look into configuring it to avoid this conflict.
