### ISSUE TITLE
Progress Formatter Error 

### ISSUE THREAD

**Issue by Huseyinaltas1** [cucumber/cucumber-js#2421]
### 👓 What did you see?

/root/project/qa/**********/node_modules/@cucumber/cucumber/src/formatter/helpers/summary_helpers.ts:77
  objects.forEach((x) => (counts[x.status] += 1))
          ^
TypeError: Cannot read properties of undefined (reading 'status')
    at /root/project/qa/**********/node_modules/@cucumber/cucumber/src/formatter/helpers/summary_helpers.ts:77:36
    at Array.forEach (<anonymous>)
    at getCountSummary (/root/project/qa/**********/node_modules/@cucumber/cucumber/src/formatter/helpers/summary_helpers.ts:77:11)
    at formatSummary (/root/project/qa/**********/node_modules/@cucumber/cucumber/src/formatter/helpers/summary_helpers.ts:53:23)
    at ProgressFormatter.logSummary (/root/project/qa/**********/node_modules/@cucumber/cucumber/src/formatter/summary_formatter.ts:72:20)
    at EventEmitter.<anonymous> (/root/project/qa/**********/node_modules/@cucumber/cucumber/src/formatter/summary_formatter.ts:27:14)
    at EventEmitter.emit (node:events:531:35)
    at EventEmitter.emit (node:domain:488:12)
    at Coordinator.onWorkerProcessClose (/root/project/qa/**********/node_modules/@cucumber/cucumber/src/runtime/parallel/coordinator.ts:184:29)
    at ChildProcess.<anonymous> (/root/project/qa/**********/node_modules/@cucumber/cucumber/src/runtime/parallel/coordinator.ts:145:12)

Exited with code exit status 1

### ✅ What did you expect to see?

Finished without any error

### 📦 Which tool/library version are you using?

Node v18.20.3
"devDependencies": {
        "@cucumber/cucumber": "10.8.0",
        "@ericblade/quagga2": "^1.8.4",
        "@playwright/test": "^1.46.1",
        "@types/json-stable-stringify": "^1.0.36",
        "@types/lodash": "^4.17.5",
        "@types/node": "^20.14.2",
        "@types/omit": "^1.0.3",
        "@types/superagent": "^8.1.7",
        "axios": "^1.7.2",
        "dotenv-flow": "^4.1.0",
        "firebase-admin": "^12.1.1",
        "googleapis": "^140.0.0",
        "json-stable-stringify": "^1.1.1",
        "lodash": "^4.17.21",
        "moment-timezone": "^0.5.45",
        "pixelmatch": "^5.3.0",
        "sharp": "^0.33.4",
        "superagent": "^10.0.1",
        "tesseract.js": "^5.1.0",
        "ts-node": "^10.9.2",
        "typescript": "^5.4.5"
    },
    "dependencies": {
        "@aws-sdk/client-api-gateway": "^3.600.0",
        "@aws-sdk/client-cognito-identity-provider": "^3.600.0",
        "@aws-sdk/client-s3": "^3.600.0",
        "@aws-sdk/client-sqs": "^3.600.0",
        "@aws-sdk/client-ssm": "^3.600.0",
        "@aws-sdk/client-sts": "^3.600.0",
        "@aws-sdk/credential-providers": "^3.600.0",
        "typesense": "^1.7.2"
    }

Build-agent version 1.0.247419-bd4d9e36 (2024-08-12T11:50:45+0000).
System information:
 Server Version: 24.0.9
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.15.0-1057-aws
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64

Starting container mcr.microsoft.com/playwright:v1.46.1-jammy
  image cache not found on this host, downloading mcr.microsoft.com/playwright:v1.46.1-jammy
v1.46.1-jammy: Pulling from playwright
9b857f539cb1: Pull complete 
e54ef8d72338: Pull complete 
f237ee1fd51a: Pull complete 
77b4793eaba5: Pull complete 
Digest: sha256:02810c978d5396bf382ab6015c25ad6bed9e39f4a41c5b9c829e9fea439274e2
Status: Downloaded newer image for mcr.microsoft.com/playwright:v1.46.1-jammy
mcr.microsoft.com/playwright:v1.46.1-jammy:
  pull stats: download 680.1MiB in 5.554s (122.4MiB/s), extract 680.1MiB in 16.946s (40.13MiB/s)
  time to create container: 668ms
Time to upload agent and config: 331.40635ms
Time to start containers: 249.897202ms

### 🔬 How could we reproduce it?

130 Scenarios
68 Features
5 Parallel Instance Via Cucumber
Runs In CircleCI 
 npx cucumber-js --require-module ts-node/register --retry ${2} --parallel ${3} --format progress --publish --tags

**Comment by Huseyinaltas1** [comment]
I checked CIrcleCI, I am having CPU memory max. Looks like root cause here. I will try increase resource memory of test image.
