### ISSUE TITLE
Revert update coffeescript version bump

### ISSUE THREAD

**Issue by samccone** [cucumber/cucumber-js#246]
98a2725894a4bb8742833309c82641b155f47e37

```bash
   at /Users/sam/Desktop/repos/pioneer/test/integration/steps/find_steps.coffee:13:26
    at /Users/sam/Desktop/repos/pioneer/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/sam/Desktop/repos/pioneer/node_modules/selenium-webdriver/lib/webdriver/promise.js:1539:20)
    at notify (/Users/sam/Desktop/repos/pioneer/node_modules/selenium-webdriver/lib/webdriver/promise.js:362:12)
```

This causes the stack traces to turn to 

```bash
   at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
```

**Comment by charlierudolph** [comment]
Closing as we are one 1.9.3 and with #398 coffee-script it going to be removed
