### ISSUE TITLE
JSON formatter doesn't work for Linux Fedora

### ISSUE THREAD

**Issue by drizgolovicha** [cucumber/cucumber-js#318]
The same configuration works fine on local windows machine, also another formatters like "summary" and "pretty" work fine.
Any suggestions?

cucumber@0.4.8

## SYSTEM:
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"

## Protractor config
exports.config = {
	"seleniumAddress": 'http://localhost:4444/wd/hub',
  "specs":["features/10.feature"],
  "multiCapabilities": [
/*
	  {
		  'browserName': "firefox",
		  'version': '30',
		  "os": "OS X",
		  "os_version": "Yosemite",
		  "build": "unknown-build",
		  "project": "1",
		  "browserstack.debug": true,
		  "acceptSslCerts": true,
		  "name": "firefox1"
	  },
*/
	{
	  'browserName': "chrome",
	  'version': '30',
		"platform": "WINDOWS",
		"os": "WINDOWS",
		"resolution": "1600x1200",
		"build": "unknown-build",
		"project": "1",
		"browserstack.debug": true,
		"acceptSslCerts": true,
		"name": "chrome1"
	}],
	"framework":"cucumber",
	"cucumberOpts":
	{
		"format": "json"
	},
	"baseUrl": "http://localhost"
};

## CONSOLE OUTPUT:
Using the selenium server at http://hub.browserstack.com/wd/hub
[launcher] Running 1 instances of WebDriver
-----------------------------------------

/home/adryzgalovich/temp/protractor/node_modules/cucumber/node_modules/gherkin/lib/gherkin/formatter/json_formatter.js:89
        if(!feature_hash['elements']) {
                        ^
TypeError: Cannot read property 'elements' of undefined
    at feature_elements (/home/adryzgalovich/temp/protractor/node_modules/cucumber/node_modules/gherkin/lib/gherkin/formatter/json_formatter.js:89:25)
    at [object Object].scenario (/home/adryzgalovich/temp/protractor/node_modules/cucumber/node_modules/gherkin/lib/gherkin/formatter/json_formatter.js:26:9)
    at handleBeforeScenarioEvent (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/listener/json_formatter.js:113:26)
    at Object.hear (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/listener.js:6:9)
    at /home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:118:51
    at processItem (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/type/collection.js:19:9)
    at iterate (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/type/collection.js:12:11)
    at Object.forEach (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/type/collection.js:23:7)
    at broadcastToListeners (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:117:19)
    at Object.broadcastEvent (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:109:7)
    at Object.broadcastBeforeEvent (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:100:12)
    at Object.broadcastEventAroundUserFunction (/home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:84:12)
    at /home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:52:14
    at /home/adryzgalovich/temp/protractor/node_modules/cucumber/lib/cucumber/support_code/library.js:71:11
    at process._tickCallback (node.js:355:11)
[launcher] Process exited with error code 1

**Comment by drizgolovicha** [comment]
On the same configuration, "After" hook contains only one parameter in callback :(

**Comment by tborychowski** [comment]
+1

**Comment by jbpros** [comment]
At first glance, this looks like an issue is in [gherkin](https://github.com/cucumber/gherkin), not cucumber.

I need to investigate this a bit further before filing an issue upstream. Also, #343 might be a blocker.

**Comment by tborychowski** [comment]
this error doesn't happen when I use protractor@1.8.0.

**Comment by jbpros** [comment]
I'm closing this as things have moved quite a lot with protractor in the meantime and we're working on gherkin3. Please reopen if this is still an issue on 0.7.0+.
