### ISSUE TITLE
Possible bug: Cannot add new Given/When/Then, getting error `SyntaxError: Invalid regular expression: missing /`

### ISSUE THREAD

**Issue by bmsoko** [cucumber/cucumber-js#446]
Hello All!
I had configured cucumber + protractor, and I firstly was splitting stepDefinitions into different files like this:
![stepdefinitions](https://cloud.githubusercontent.com/assets/3765964/10786123/59c7aaf6-7d47-11e5-8339-91b54d3acea9.png)

When I created new features files, and started running, cucumber/protractor did not recognized these new steps I was adding to the other files. So I decided to move all the new steps into the same file.

But when I run, although they are well written (checked and compared thousands of times)  I getting this error:

```javascript
$ ./node_modules/protractor/bin/protractor conf.js
util.puts: Use console.log instead
Starting selenium standalone server...
util.puts: Use console.log instead
Selenium standalone server started at http://192.168.0.101:53853/wd/hub
[launcher] Error: /Users/brunosoko/Documents/Dev/Personal/test2/features/step_definitions/homepage/stepsDefinitions.js:50
    this.Then(/^I see the Gallery widget $/, function(done){
              ^
SyntaxError: Invalid regular expression: missing /
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/brunosoko/Documents/Dev/Personal/test2/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (native)
    at Object.wrapper (/Users/brunosoko/Documents/Dev/Personal/test2/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
```
I've the following versions running of protractor and cucumber:

```JSON
  "devDependencies": {
    "chai": "*",
    "chai-as-promised": "^5.1.0",
    "cucumber": "~0.6.0",
    "protractor": "1.4.0",
    "protractor-cucumber-junit": "latest",
    "protractor-html-screenshot-reporter": "^0.0.21",
    "selenium-webdriver": "2.47.0"
  },
```
These are my stepDefinition:

Update 1: Adding complete file
```javascript
var CarouselWidgetPage = require('../../../page-objects/CarouselWidgetPage.js');
var TestUtilsPage = require('../../../page-objects/utils/TestUtils.js');
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
var expect = chai.expect;


module.exports = function() {
    var CarouselPage;
    var TestUtils;

    this.Before(function (){
        CarouselPage = new CarouselWidgetPage();
        TestUtils = new TestUtilsPage();
    });


    /*Given*/
    this.Given(/^I am at the homepage$/, function (done) {
        browser.get('').then(function(){
            CarouselPage.clickOutSidePopUp();
            done();
        });
    });
    this.Given(/^I can see that images and videos are present on the widget$/ , function (done) {
        expect(CarouselPage.checkMediaSource()).to.eventually.be.true;
        done();
    });


    this.When(/^I select an image  or video$/, function (done) {
        CarouselPage.getMedia(1).click();
        done();
    });


    /*Then*/
    this.Then(/^I see that Carousel Widget is correctly displayed$/, function(done){
        expect(CarouselPage.carouselContainer.isPresent()).to.eventually.be.true;
        done();
    });

    this.Then(/^I see the viewer modal   $/, function(done){
        expect(ViewerModal.viewerContainer.isPresent()).to.eventually.be.true;
        done();
    });

    this.Then(/^I see the Gallery widget $/, function(done){
        expect(CarouselPage.carouselContainer.isPresent()).to.eventually.be.true;
        done();
    });

    });
```

So, what am I doing wrong? Do I need to clear some cache? is this a bug with the versions I am using?

Thanks!

*NOTE:*
What also called my attention is that if I even comment the whole step, I see this on the console

```javascript
./node_modules/protractor/bin/protractor conf.js
util.puts: Use console.log instead
Starting selenium standalone server...
util.puts: Use console.log instead
Selenium standalone server started at http://192.168.0.101:58696/wd/hub
[launcher] Error: /Users/brunosoko/Documents/Dev/Personal/test2/features/step_definitions/homepage/stepsDefinitions.js:24
    //this.When(/^I select an image  or video$/, function (done) {
                                        ^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/brunosoko/Documents/Dev/Personal/test2/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (native)
    at Object.wrapper (/Users/brunosoko/Documents/Dev/Personal/test2/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
```
Here's my `conf.js` file: 
```javascript
//Report for tests
var HtmlReporter = require('protractor-html-screenshot-reporter');
var reporter = new HtmlReporter({
    baseDirectory: './protractor-result', // a location to store screen shots.
    docTitle: 'Report Test Summary',
    docName: 'protractor-tests-report.html'
});

exports.config = {
    specs: [
        'features/*.feature'
    ],
    baseUrl: "http://www.page.com",
    capabilities:
        {
            'browserName': 'chrome',
            'specs':'features/**/*.feature'
        },
    framework: 'cucumber',
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    cucumberOpts: {
        require: 'features/step_definitions/**/*.js',
        format: 'pretty'
    },
    resultJsonOutputFile: 'report.json',

    onPrepare: function () {

        browser.driver.manage().window().maximize();

        browser.ignoreSynchronization = true;

        browser.manage().timeouts().implicitlyWait(20000);

        browser.getCapabilities().then(function (cap) {
            browserName = cap.caps_.browserName;
        });

    }
};
```

**Comment by charlierudolph** [comment]
Can you please give the entire file contents of your step definitions file that is erroring?

**Comment by bmsoko** [comment]
Udpdate! Thanks for looking at it!

**Comment by charlierudolph** [comment]
If I just copy the failing regexp, from you step file and run it in node I get the same error. 

Copying your failing regexps into http://jdstiles.com/java/cct.html, you can see there is a character with charcode 8232 which is a line separator.

Removing that character appears to make things work.

**Comment by bmsoko** [comment]
Hows that even possible?!?! I don't understand! I typed it! as usual! but what you suggested worked! thanks a lot for your answer! 
I had posted his scenario in stackoverflow: http://stackoverflow.com/questions/33389270/cannot-add-new-given-when-then-getting-error-syntaxerror-invalid-regular-expr if you want, you can post it there and I'll accept it! thanks much for your time!

**Comment by bmsoko** [comment]
Last question for you @charlierudolph! how can I split stepsDefinitions.js into different files? when I started doing that, is like the ones that were in different files where not recognized, therefore not run! 
Appreciate what you done! I'll look fw to create a mini-tutorial for people like me :smile_cat:

**Comment by charlierudolph** [comment]
Looking at protractor config, the cucumberOpts has `require: 'features/step_definitions/**/*.js'`. Thus if you step definitions don't match that, they won't be picked up. See [here](https://github.com/cucumber/cucumber-js#requiring-support-files) for more documentation on the require options.
