### ISSUE TITLE
Terminates prematurely without any errors / stack trace.

### ISSUE THREAD

**Issue by lawrence-yu** [cucumber/cucumber-js#452]
When I try to run my feature/scenario suite, it consistently prematurely exits at around the same 1-3 steps, without any exception/stack trace. 

If I run the cucumber-js command directly, then it appears to just stop execution; when I run the same script as part of  ```npm run``` then I at least get some more information (npm-debug.log copied below).

The first time I experienced this, I had a fully passing suite on one machine, and cloned my repo on another machine and ran the same suite. After a lot of messing around, I found that when I switched from the x64 to the x86 version of NodeJS on this new computer it fixed the issue.

However, I am again experiencing this behavior after implementing more scenarios/steps, this time on the original machine (just trying to throw as many data points out there, since the whole thing is very cryptic).

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lawrence.yu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cucumber' ]
2 info using npm@3.3.12
3 info using node@v5.0.0
4 verbose run-script [ 'precucumber', 'cucumber', 'postcucumber' ]
5 info lifecycle react-test-page@1.0.0~precucumber: react-test-page@1.0.0
6 silly lifecycle react-test-page@1.0.0~precucumber: no script for precucumber, continuing
7 info lifecycle react-test-page@1.0.0~cucumber: react-test-page@1.0.0
8 verbose lifecycle react-test-page@1.0.0~cucumber: unsafe-perm in lifecycle true
9 verbose lifecycle react-test-page@1.0.0~cucumber: PATH: C:\Users\lawrence.yu\AppData\Roaming\npm\node_modules\npm\bin.... (truncating cause it's long)
10 verbose lifecycle react-test-page@1.0.0~cucumber: CWD: c:\data\programming\git\CQ_Bread_Calculator
11 silly lifecycle react-test-page@1.0.0~cucumber: Args: [ '/d /s /c',
11 silly lifecycle   'cucumber-js test/ -r ./test/features/step_definitions --no-snippets --fail-fast --compiler js:babel/register' ]
12 silly lifecycle react-test-page@1.0.0~cucumber: Returned: code: 3221225725  signal: null
13 info lifecycle react-test-page@1.0.0~cucumber: Failed to exec cucumber script
14 verbose stack Error: react-test-page@1.0.0 cucumber: `cucumber-js test/ -r ./test/features/step_definitions --no-snippets --fail-fast --compiler js:babel/register`
14 verbose stack Exit status 3221225725
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\lawrence.yu\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\lawrence.yu\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-test-page@1.0.0
16 verbose cwd c:\data\programming\git\CQ_Bread_Calculator
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\lawrence.yu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "cucumber"
19 error node v5.0.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error react-test-page@1.0.0 cucumber: `cucumber-js test/ -r ./test/features/step_definitions --no-snippets --fail-fast --compiler js:babel/register`
22 error Exit status 3221225725
23 error Failed at the react-test-page@1.0.0 cucumber script 'cucumber-js test/ -r ./test/features/step_definitions --no-snippets --fail-fast --compiler js:babel/register'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-test-page package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cucumber-js test/ -r ./test/features/step_definitions --no-snippets --fail-fast --compiler js:babel/register
23 error You can get their info via:
23 error     npm owner ls react-test-page
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by charlierudolph** [comment]
Can you please share what is in your step definitions?

**Comment by lawrence-yu** [comment]
I pasted a decent size sample of my step definitions below, as it's pretty much the same pattern throughout all the steps.

They are all just testing a single Reactor from NuclearJS.  This Reactor is instantiated in the '../../src/js/reactor/reactor' module. Its stores are registered just once at the beginning of this module, and then the instance is passed around and reset for each scenario (I'm using "the initial application state" step definition pretty much as a beforeEach in all of my scenarios).

```
import Immutable from 'immutable'
import _ from 'lodash'
import should from 'should'

import Utils from '../utils'

import reactor from '../../../src/js/reactor/reactor'
import getters from '../../../src/js/getters/getters'
import HeroSettingsStore from '../../../src/js/stores/hero-settings-store'
import HeroExpStore from '../../../src/js/stores/hero-exp-store'
import TrainingExpStore from '../../../src/js/stores/training-exp-store'

import SelectedBreadStore from '../../../src/js/stores/selected-bread-store'

import actions from '../../../src/js/actions/actions'

reactor.registerStores({
	'heroSettings'   : HeroSettingsStore,
	'heroExp'        : HeroExpStore,
	'trainingExp'    : TrainingExpStore,
	'selectedBreads' : SelectedBreadStore,
})

function steps() {

	this.Given('the initial application state', (callback) => {
		this.reactor = reactor
		this.reactor.reset()
		this.getters = getters
		this.actions = actions
		callback()
	})

	this.Then('the available ranks should be [$lowerBound...$upperBound]', (lowerBound, upperBound, callback) => {
		lowerBound = Number(lowerBound)
		upperBound = Number(upperBound)
		const expected = Immutable.fromJS(_.range(lowerBound, upperBound + 1))

		const { availableRanks } = this.getters
		this.reactor.evaluate(availableRanks).should.eql(expected)
		callback()
	})

	// A number of skipped steps here to reduce length, as it is more of the step-style of these here
	// .
	// .
	// .

	this.Then('the selected target training should be $targetTraining', (targetTraining, callback) => {
		targetTraining = Number(targetTraining)
		const { selectedTargetTraining } = getters
		this.reactor.evaluate(selectedTargetTraining).should.eql(targetTraining)
		callback()
	})

	this.Then('the hero exp should be $exp', (exp, callback) => {
		const { heroExp } = this.getters
		exp = Number(exp)
		this.reactor.evaluate(heroExp).should.eql(exp)
		callback()
	})

	this.When('I set the hero exp to $exp', (exp, callback) => {
		this.actions.setHeroExp(exp)
		callback()
	})

	this.When('I set the target training to $training', (training, callback) => {
		training = Number(training)
		this.actions.setTargetTraining(training)
		callback()
	})

	this.Then('the total needed exp is $exp', (exp, callback) => {
		const { totalNeededExp } = this.getters
		exp = Number(exp)
		this.reactor.evaluate(totalNeededExp).should.eql(exp)
		callback()
	})

	this.When('I select a bread with id $breadId', (breadId, callback) => {
		this.actions.selectBread(breadId)
		callback()
	})

	this.Then('there should be $numberOfBreads selected breads', (numberOfBreads, callback) => {
		numberOfBreads = Number(numberOfBreads)
		const { selectedBreads } = this.getters
		this.reactor.evaluate(selectedBreads).size.should.eql(numberOfBreads)
		callback()
	})

	this.Then('the selected breads should be "$breadsArray"', (breadsArray, callback) => {
		const { selectedBreads } = this.getters
		const expectedBreads = Immutable.List(Utils.toArray(breadsArray))
		const stateBreads = this.reactor.evaluate(selectedBreads)
		Immutable.is(stateBreads, expectedBreads).should.be.true()
		callback()
	})
}

module.exports = steps
```

**Comment by lawrence-yu** [comment]
I believe I found the root issue. The lack of traceable errors seems to come from doing this on Windows; once I tried on Ubuntu it still failed, but with at least some more information.

The root issue seemed to be ```RangeError: Maximum call stack size exceeded```

I googled around a bit with this in the context of cucumber-js, and found a commit of someone switching, in their step definitions, the ```callback()``` statement at the end of each step to ```process.nextTick(callback)``` to guard against this error.

I tried this and it seems to have resolved the issue so far (though, the issue had a reputation of coming and going, so I will have to see).

**Comment by charlierudolph** [comment]
On a related note cucumber-js now supports synchronous steps so for any synchronous operations, you can just remove the callback.

**Comment by lawrence-yu** [comment]
The synchronous steps was something that I did try earlier to solve this issue. However, it did not help. 

It seems like there’s something about the timing of the execution that’s causing the stack growth that the ‘’‘process.nextTick’’’ is helping prevent. 

So far on a couple machines I’ve been able to consistently produce the error on a suite of scenarios, and have them consistently work after adding the guard to the steps.

**Comment by grofit** [comment]
Not sure if it is related but sounds similar to my scenario, I posted on SO a few days ago and have been asking on gitter for a week or so:

http://stackoverflow.com/questions/34862560/cucumber-js-not-running-step-but-saying-its-passed-then-skipping-subsequent-step

I get no error and a step starts but never executes, flags as a success then skips subsequent steps.

**Comment by charlierudolph** [comment]
Can you please create a small example that illustrates your problem so I can reproduce and debug? For example, just a single feature and step definition file with the problem code.

**Comment by grofit** [comment]
Well this is part of the problem it only seems to exhibit on larger projects, I have smaller projects with cucumber and its fine. If you can tell me a way to turn on additional debug or anything I can try providing more output.

**Comment by grofit** [comment]
I am not sure if this helps or confuses things, however when I try to run the tests with:

```
cucumber-js --format summary
path.js:174
  resolvedTail = normalizeArray(resolvedTail.split(/[\\\/]+/),
                                             ^

RangeError: Maximum call stack size exceeded
    at String.split (native)
    at Object.win32.resolve (path.js:174:46)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

if I were to run with `--format progress` it doesnt give me the error, and seems to run everything fine (well I get errors but it runs at least).

**Comment by grofit** [comment]
OH something else which may help I can see the output:

```
The following steps have multiple matching definitions:

"I send a post request to users/password/change with payload" matches:
/^I send a (get|put|post|delete) request to (.*)$/              # features\step_definitions\shared-step-definitions.js:99
/^I send a (get|put|post|delete) request to (.*) with payload$/ # features\step_definitions\shared-step-definitions.js:126
```

And this is where my tests were randomly failing, so I am not sure if behind the scenes it is not sure what to match and just blows up without reporting it when using certain reporters.
