### ISSUE TITLE
--compiler es6:babel-core/register does not work

### ISSUE THREAD

**Issue by artemjackson** [cucumber/cucumber-js#480]
Seems that cucumber compiler does not work with `es6` and `babel-core/register`
`--compiler es6:babel-core/register`
Error occured:
`Error: SyntaxError: Unexpected token import`

What's I'm doing wrong?

Tried with
```
"babel-core": "6.3.21",
"cucumber": "0.9.2"
```
Issue comes from this topic https://github.com/mattfritz/protractor-cucumber-framework/issues/15

**Comment by charlierudolph** [comment]
Everything appears correct. What is the stacktrace for the error?

**Comment by artemjackson** [comment]
```
[launcher] Error: SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/home/jackson/e2e/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jackson/e2e/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/jackson/e2e/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (native)
[launcher] Process exited with error code 100
```

**Comment by artemjackson** [comment]
Sorry, it was my bad.
Since Babel 6 uses `.babelrc` i forgot to add
```
{
  "presets": ["es2015"]
}
```
Now everything works well. So it issue does not relate to cucumber itself.

**Comment by maharshioza** [comment]
+1
