### ISSUE TITLE
Error: Cannot find module 'tmp'

### ISSUE THREAD

**Issue by machineghost** [cucumber/cucumber-js#493]
I recently installed and attempted to use cucumberjs for the first time, but when I ran it I got the following error:

    $ cucumberjs test.txt
    module.js:340
        throw err;
        ^

    Error: Cannot find module 'tmp'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:289:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.hooks (/home/me/static/node_modules/cucumber/features/support/hooks.js:3:13)    
        at /usr/lib/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:65:25
        at Array.forEach (native)
        at Object.wrapper (/usr/lib/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
        at Object.initializer (/usr/lib/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:23:37)
        at Object.Library (/usr/lib/node_modules/cucumber/lib/cucumber/support_code/library.js:123:25)

Not sure if this is a cucumber error or some sort of problem with my setup, but any help would be appreciated.

**Comment by charlierudolph** [comment]
Appears to be a problem with your setup. Have you run `npm install tmp`?

**Comment by charlierudolph** [comment]
@machineghost any update? If you still need help, please provide more information so I can reproduce your issue.

**Comment by machineghost** [comment]
Sorry, I haven't had time to get back to Cucumber lately. I'm pretty sure `npm install tmp` isn't going to help (I don't even know what `tmp` is), but I'm also convinced that this is some sort of problem with my local setup which just happened to manifest when trying to use Cucumber (ie. it doesn't seem to be a Cucumber problem).

Apologies for (what is probably) a false flag.
