### ISSUE TITLE
Is there a dependency missing from package.json?

### ISSUE THREAD

**Issue by deaks-kt** [cucumber/cucumber-js#552]
Hi,  encountered an odd problem whilst investigating a different problem.  For v0.9.5, v0.10.0 and v0.10.1 I get an error when I try to use cucumber in a clean environment.

e.g.

```
bash-3.2$ mkdir /tmp/cuke0.9.5
bash-3.2$ cd /tmp/cuke0.9.5
bash-3.2$ cp ../cuke0.10.1/background.feature .
bash-3.2$ cat background.feature 
Feature: A funny old thing

Scenario: Bing bang bosh

    Given cucumber v0.10.1
    When used against this feature
    Then it tries to call getUri on an undefined var

bash-3.2$ npm install cucumber@0.9.5
cucumber@0.9.5 node_modules/cucumber
├── callsite@1.0.0
├── colors@1.1.2
├── stack-chain@1.3.7
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── cli-table@0.3.1 (colors@1.0.3)
├── camel-case@1.2.2 (upper-case@1.1.3, sentence-case@1.1.3)
├── cucumber-html@0.2.3
├── glob@7.0.3 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.3, minimatch@3.0.0)
├── gherkin@2.12.2
├── lodash@4.8.2
└── duration@0.2.0 (d@0.1.1, es5-ext@0.10.11)
bash-3.2$ node_modules/.bin/cucumber.js background.feature 
/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/support_code/library.js:122
  supportCodeDefinition.call(supportCodeHelper);
                       ^

TypeError: Cannot read property 'call' of undefined
    at Object.Library (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/support_code/library.js:122:24)
    at Function.VolatileConfiguration (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/volatile_configuration.js:3:49)
    at Object.Cucumber (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber.js:2:32)
    at /private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:65:25
    at Array.forEach (native)
    at Object.wrapper (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
    at Object.initializer (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:24:41)
    at Object.Library (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/support_code/library.js:122:25)
    at Object.getSupportCodeLibrary (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (/private/tmp/cuke0.9.5/node_modules/cucumber/lib/cucumber/cli/configuration.js:128:32)
```

In my development environment I get the usual output with the example steps.  I suspected there was a package I have in my development environment that does not exist in this one, so I tried the following:

```
bash-3.2$ cd node_modules/cucumber/
bash-3.2$ npm install
```

This then installs all the devDependencies for cucumber correctly, but I still get the same error.

Any hints on how best to debug this?

**Comment by deaks-kt** [comment]
Forget it - I am officially stupid....  I forgot to put the background.feature file in the ./feature directory so it was trying to load every blasted .js script in node_modules as a support script <sigh>
