### ISSUE TITLE
Error running npm install -g cucumberjs

### ISSUE THREAD

**Issue by rcbop** [cucumber/cucumber-js#560]
Hello,

I'm currently experiencing the following error after running npm install -g cucumberjs
```
⇒  npm install cucumberjs -g
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cucumberjs" "-g"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cucumberjs
npm ERR! 404
npm ERR! 404  'cucumberjs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cucumberjs',
1 verbose cli   '-g' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cucumberjs
8 silly fetchNamedPackageData cucumberjs
9 silly mapToRegistry name cucumberjs
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/cucumberjs
13 verbose request uri https://registry.npmjs.org/cucumberjs
14 verbose request no auth needed
15 info attempt registry request try #1 at 5:03:49 PM
16 verbose request id 8d0be62f6213fff2
17 http request GET https://registry.npmjs.org/cucumberjs
18 http 404 https://registry.npmjs.org/cucumberjs
19 verbose headers { 'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=0',
19 verbose headers   'content-length': '2',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Fri, 15 Apr 2016 20:03:50 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '0',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-iad2146-IAD',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1460750630.533526,VS0,VE21',
19 verbose headers   vary: 'Accept-Encoding' }
20 silly get cb [ 404,
20 silly get   { 'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=0',
20 silly get     'content-length': '2',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Fri, 15 Apr 2016 20:03:50 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-iad2146-IAD',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1460750630.533526,VS0,VE21',
20 silly get     vary: 'Accept-Encoding' } ]
21 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/cucumberjs
21 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
21 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
21 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
21 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
21 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
21 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
21 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1035:10)
21 silly fetchPackageMetaData     at emitOne (events.js:95:20)
21 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
21 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:962:12)
21 silly fetchPackageMetaData  error for cucumberjs { [Error: Registry returned 404 for GET on https://registry.npmjs.org/cucumberjs] pkgid: 'cucumberjs', statusCode: 404, code: 'E404' }
22 silly rollbackFailedOptional Starting
23 silly rollbackFailedOptional Finishing
24 silly runTopLevelLifecycles Starting
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/cucumberjs
27 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
27 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
27 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
27 verbose stack     at emitTwo (events.js:100:13)
27 verbose stack     at Request.emit (events.js:185:7)
27 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1035:10)
27 verbose stack     at emitOne (events.js:95:20)
27 verbose stack     at Request.emit (events.js:182:7)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:962:12)
28 verbose statusCode 404
29 verbose pkgid cucumberjs
30 verbose cwd /Users/rogerio.c.peixoto/git/backoffice
31 error Darwin 14.5.0
32 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cucumberjs" "-g"
33 error node v5.6.0
34 error npm  v3.6.0
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/cucumberjs
37 error 404
38 error 404 'cucumberjs' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
```

**Comment by charlierudolph** [comment]
The npm module is actually named `cucumber`. Please try `npm install -g cucumber`

**Comment by rcbop** [comment]
ops.. sorry I guess I've got mixed up with this https://www.npmjs.com/package/cucumberjs-chromedriver.

thanks for the clarification
