### ISSUE TITLE
feature-test doesn't work with Node.js 6.0

### ISSUE THREAD

**Issue by pinxue** [cucumber/cucumber-js#575]
So far cucumber-js runs well with Node.js 6.0 (released since Apr. 26), but feature-test fails (npm 3.8.6, node v6.0.0).

$ ./bin/cucumber.js --fail-fast -p build
.....F

Failures:

1) Scenario: too many arguments - features/after_hook_interface.feature:21
   Step: And the output contains the text: - features/after_hook_interface.feature:34
   Step Definition: features/step_definitions/cli_steps.js:58
   Message:
     Error: Expected output to contain the following:
     function has 3 arguments, should have 0 or 1 (if synchronous or returning a promise) or 2 (if accepting a callback)
     Got:

     Error:
     Error: Command failed: .../cucumber-js/bin/cucumber.js
     fs.js:1568
       return binding.realpath(pathModule._makeLong(path), options.encoding);
                      ^

     Error: ENOENT: no such file or directory, realpath ''
         at Error (native)
         at Object.realpathSync (fs.js:1568:18)
         at Object.expandPathWithExtensions (.../cucumber-js/lib/cucumber/cli/path_expander.js:14:23)
         at .../cucumber-js/lib/cucumber/cli/path_expander.js:8:27
         at Array.map (native)
         at Object.expandPathsWithExtensions (.../cucumber-js/lib/cucumber/cli/path_expander.js:7:31)
         at Object.expandPaths (.../cucumber-js/lib/cucumber/cli/feature_path_expander.js:9:38)
         at Function.Configuration (.../cucumber-js/lib/cucumber/cli/configuration.js:21:63)
         at getConfiguration (.../cucumber-js/lib/cucumber/cli.js:46:38)
         at Object.run (.../cucumber-js/lib/cucumber/cli.js:52:27)
     .
     stderr:
     fs.js:1568
       return binding.realpath(pathModule._makeLong(path), options.encoding);
                      ^

     Error: ENOENT: no such file or directory, realpath ''
         at Error (native)
         at Object.realpathSync (fs.js:1568:18)
         at Object.expandPathWithExtensions (.../cucumber-js/lib/cucu

**Comment by charlierudolph** [comment]
Thanks for the heads up. Able to reproduce and found a fix. I'll add node 6 to our CI matrix
