### ISSUE TITLE
cucumber 1.0.0 regression (tags + background?)

### ISSUE THREAD

**Issue by bricas** [cucumber/cucumber-js#585]
Understandably 1.0.0 is a major release and one can expect a few hiccups, though there are no hints in the changelog about what might break.

I have a test that starts with:

```
Feature: Login off-site

  @proxy
  Background: Override Page Load Timeout
    Given I set pageLoadTimeout to 30000

  Scenario: Site proxy login accessible off-site
    Given I visit https://proxy.example.com/login
    (etc)
```

Where this was okay in 0.10.3 (i didn't test with 0.10.4) it fails outright in 1.0.0:

```
/home/bricas/site-tests/node_modules/cucumber/lib/cucumber/parser.js:21
          throw e;
          ^
CompositeParserException: Parser errors:
(4:3): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Background: Override Page Load Timeout'
(5:5): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Given I set pageLoadTimeout to 30000'
path: /home/bricas/site-tests/features/core/authentication-proxy.feature
    at Function.Errors.CompositeParserException.create (/home/bricas/site-tests/node_modules/cucumber/node_modules/gherkin/lib/gherkin/errors.js:27:13)
    at Parser.parse (/home/bricas/site-tests/node_modules/cucumber/node_modules/gherkin/lib/gherkin/parser.js:79:45)
    at /home/bricas/site-tests/node_modules/cucumber/lib/cucumber/parser.js:18:36
    at Array.forEach (native)
    at Object.parse (/home/bricas/site-tests/node_modules/cucumber/lib/cucumber/parser.js:12:22)
    at Object.getFeatures (/home/bricas/site-tests/node_modules/cucumber/lib/cucumber/runtime.js:38:35)
    at Object.start (/home/bricas/site-tests/node_modules/cucumber/lib/cucumber/runtime.js:11:27)
    at Object.run (/home/bricas/site-tests/node_modules/cucumber/lib/cucumber/cli.js:58:15)
    at Object.<anonymous> (/home/bricas/site-tests/node_modules/cucumber/bin/cucumber.js:4:5)
    at Module._compile (module.js:409:26)
```

It seems likely it's the way i'm using the tag next to "background" -- but should this be a regression?

Thanks in advance.

**Comment by charlierudolph** [comment]
With 1.0.0 we upgraded to gherkin 4. It appears gherkin 4 does not allow tags on backgrounds. I'd suggest moving the tag to the feature.

**Comment by charlierudolph** [comment]
Gherkin is the parser we use for feature files

**Comment by bricas** [comment]
Indeed, moving the tag above the Feature seems to be working. thanks.
