### ISSUE TITLE
Version 1.3.1 breaks on `babel-node` polyfied environment

### ISSUE THREAD

**Issue by Spy-Seth** [cucumber/cucumber-js#652]
I'm trying to upgrade cucumber from `v1.2.2` to `v1.3.1`. But the new version seems to not be compatible my installation. 

I'm using cucumberjs with ES2015 step files. For now, I'm using `babel-node` to polyfill the environment:
```
$ node --harmony ./node_modules/.bin/babel-node ./node_modules/.bin/cucumberjs
```

After upgrading to the `v1.3.1` version, I've an error throw at startup:
```
$ node --harmony ./node_modules/.bin/babel-node ./node_modules/.bin/cucumberjs
/app/features/fixtures/EventSourcing/Car.js:27
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
                                                                                            ^

TypeError: Cannot call a class as a function
    at _classCallCheck (/app/features/fixtures/EventSourcing/Car.js:27:99)
    at Object.Car (/app/features/fixtures/EventSourcing/Car.js:12:50)
    at /app/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:67:33
    at Array.forEach (native)
    at Object.wrapper (/app/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
    at Object.initializer (/app/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:24:41)
    at Object.Library (/app/node_modules/cucumber/lib/cucumber/support_code/library.js:133:25)
    at Object.getSupportCodeLibrary (/app/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (/app/node_modules/cucumber/lib/cucumber/cli/configuration.js:128:32)
    at Object.getSupportCodeLibrary (/app/node_modules/cucumber/lib/cucumber/runtime.js:44:46)
```
The `Car.js` file is directly imported in one of my step file `import Car from './../fixtures/EventSourcing/Car';` and looks like this: https://gist.github.com/Spy-Seth/2fed28afa3e96e8ee7a1946a1c1e43b3 (a simple exported ES2015 class).

I do not find a way to make this configuration working with the new version of cucumbejs. Do I do wrong something?

**Comment by charlierudolph** [comment]
1.3.0 [added es6 export default function module support](https://github.com/cucumber/cucumber-js/pull/621). 

This has been something I've disliked about cucumber-js. Every support file is required and if it exports a function them it calls it. The problem is as what you ran into when you classes since they are technically functions.

One workaround for this (which should probably just be the suggested project setup) is to put any helper classes in a different folder and use `--require` for complete control of what cucumber-js loads. For example make your default profile require `feature/step_definitions` and `features/support` (which holds the hook / world / timeout configs) while your classes and other files which cucumber-js shouldn't require directly live in another folder like `features/helpers`. cucumber-js could then validate all required files export a function.

**Comment by Spy-Seth** [comment]
Thanks for your answer. 

As I understand the solution for small project, it seems to be really complicated to do in a big project:I will have to many required file to manage to have all my features working. 

I'm not sure about the right solution for people who a doing ES2015 (or more recent): an option to disable this feature and let the user to use `babel-node` (like I did), or make cucumber reusing the project babel configuration (like https://github.com/avajs/ava does for example).

**Comment by charlierudolph** [comment]
Can you explain more the possible solutions you are thinking about? I don't see this issue as being babel specific.I think it would be good to change how cucumber loads step definitions and other things to not just run any exported function but I'm uncertain at the moment how to do that. I'll create a new issue to track this.

**Comment by Spy-Seth** [comment]
In a more thought, if you are familiar with PHP, the [Behat](http://behat.org/en/latest/) project have strong proposal on how to deal with step definition and world (they call it context, and are multiple). Their proposal lead to more structure and forbid a lot of usage (generally wrong usage). It also imply that the library (here `cucumber-js`) has more job to do. I not saying that this library should follow this path but it is an idea.

Instead of automatically load file, you could look on being more configurable. It could help to avoid auto-loading.
