### ISSUE TITLE
Errors in this.AfterStep crashes cucumberjs

### ISSUE THREAD

**Issue by floribon** [cucumber/cucumber-js#658]
Given these hooks:

```
this.After(() => {
  throw new Error('boom scenario');
});

this.AfterStep(() => {
  throw new Error('boom step');
});
```

The first block will properly fail and terminate the scenario with formatters and everything.

The second block will crash the process:

> Error: .../runtime.js:152 boom step
      at .../features/step_definitions/runtime.js:153:11
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
make: *** [test] Error 1

I am pretty sure the same happens using promises/callbacks from these hooks. 
`callback(error)`only properly works from `this.After`.

**Comment by charlierudolph** [comment]
`this.AfterStep(fn)` is a shorthand for `this.registerHandler('AfterStep', fn)`. Handlers are not involved in the test running process and those errors are considered fatal. I will add some documentation for this, but that is the expected behavior currently. Do you have a reason for not wanting this to terminate the process?

**Comment by floribon** [comment]
Yes. For my personal use case, I am gathering any `console.error` or uncaught exception that would happen within the web app. At the end of any step, if this collection of browser-side errors is not empty, I want to fail the test. Currently I have to set a flag and wait until the After hook to be able to fail the scenario.

A user may want to fail a scenario at the end of a given step for various reasons (step took too long, report missing, etc). It seems weird to crash the process when an error is properly passed to a callback, and this is not consistent with other hooks (I don't know the internals but to me this.After and this.AfterStep should have a similar api).

**Comment by charlierudolph** [comment]
I'm planning on removing `this.AfterStep` in 2.0 since its syntactic sugar for `registerHandler` and because they do behave differently. 

If a step should fail, I believe thats the responsibility of the step. Since this appears to be needed for all steps or something like it, I'd prefer we implement a separate generic way for wrapping step definitions so you can do your custom pre / post processing which appears to be something a lot of people are doing.

**Comment by floribon** [comment]
I'm totally fine using another set of pre/post processors indeed, but the need to fail a step from some condition executed after each step is real.

If this.AfterStep is to become obsolete, do you recommend changing them by `registerHandler`? Does this apply to every hook (AfterStep, Before, StepResult, AfterFeatures, BeforeFeature, etc?)

Please update the wiki as for now `this.After` seems to be the recommended way: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md

**Comment by charlierudolph** [comment]
There are two separate entities here in my mind.

`this.After` / `this.Before` - are used to define hooks which receive the same world instance as steps.

`this.AfterStep` / `this.AfterScenario` / `this.BeforeFeature` etc - syntactic sugar for registerHandler which is used to hook into the cucumber lifecycle for purposes other than running tests. The primary exception to this that I'm aware of is using the `AfterFeatures`/ `BeforeFeatures` events for setting up resources shared between scenarios but would prefer if we eventually move to `this.AfterAll` / `this.BeforeAll` to make a more clean break between the two.

**Comment by klokovas** [comment]
Hi @floribon! 
I have a similar problem. You solved it?

**Comment by charlierudolph** [comment]
In `2.0.0-rc1`, `this.AfterStep` / `this.AfterScenario` / `this.BeforeFeature` were removed in favor of using `registerHandler` with the event name.

---

@floribon can you please give an example of needing to fail a step in `AfterStep` instead of in the actual step itself?

**Comment by floribon** [comment]
@charlierudolph I tried to explain it in a prior comment. If there is any `console.error` or uncaught `Exception` thrown during any given step within my web app, I want to fail this step and start working on a fix.

Let's simplify things saying that I have a global flag that tells me whether an error occurred or not. At the end of any step, if that flag is true, then I want to abort the scenario and mark it as failing. Do you know if the Ruby implementation of Cucumber allow failing from a hook?

More generally, this may be debatable, but I don't think a controlled error properly given to a callback using nodejs standard syntax should crash the process at an obscure location, as if it was not expected. At the very least we should get some message to avoid panic such as `"AfterStep hook has finished with an error, terminating process"`

**Comment by charlierudolph** [comment]
Cucumber-js already catches uncaught errors and fails the step and scenario. 

I don't know about Ruby's support for failing from an event handler and I don't know if they even have event handlers.

The updated error message sounds good to me.

**Comment by floribon** [comment]
@charlierudolph I am talking about errors happening on the browser while selenium is manipulating it. That's out of cucumber context, but that's an example where I want some custom step checking within a hook.

My current workaround is to fail during the `After` scenario real hook which does accept an error on callback, so I guess I'll keep doing it that way. Only downside is that I need to wait until the scenario finishes even if my first step was not valid.

**Comment by charlierudolph** [comment]
Sounds like this could be a use for [setDefinitionFunctionWrapper](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#thissetdefinitionfunctionwrapperfn)

**Comment by charlierudolph** [comment]
@floribon any update on this? Does `setDefinitionFunctionWrapper` solve your issue?

**Comment by floribon** [comment]
@charlierudolph I tried but couldn't figure out how to use it. Any variation of this would break my suite, do you have any example of usage?

```
  this.setDefinitionFunctionWrapper(function(fn) {
    return function(...args) {
      return fn.call(this, ...args);
    };
  });
```

**Comment by charlierudolph** [comment]
Here is an [example](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md#definition-function-wrapper)

I used your code snippet and added it to the cucumber-js test suite and it worked fine. What error are you getting?

**Comment by charlierudolph** [comment]
Updated handler errors released in 2.0.0-rc.6

**Comment by kirankabadi7** [comment]
I want to close the browser whenever my teat scenario fails. How can I handle this via Hook

**Comment by charlierudolph** [comment]
@kirankabadi7 please look through the docs first next time (links on the readme): https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#afteroptions-fn. `result.status` of the first argument is probably what you are looking for
