### ISSUE TITLE
Unable to get the --world-parameters option working

### ISSUE THREAD

**Issue by ashutoshmittal2309** [cucumber/cucumber-js#675]
Hi
I am trying to use --world-parameters to set a flag "debug=true" for my scripts so that i can print some extra information if this value is set.
Below is the command line i am using -

$ **./node_modules/cucumber/bin/cucumber.js features/ -r step-definitions/ --world-parameters** **{"debug":true}**
/upf/test/node_modules/cucumber/lib/cucumber/cli.js:12
      throw new Error('--world-parameters passed invalid JSON: ' + error.message + ': ' + str);
      ^

Error: --world-parameters passed invalid JSON: Unexpected token d: {debug:true}
    at mergeWorldParametersJson (/upf/test/node_modules/cucumber/lib/cucumber/cli.js:12:13)
    at Command.<anonymous> (/upf/test/node_modules/cucumber/node_modules/commander/index.js:395:35)
    at emitOne (events.js:77:13)
    at Command.emit (events.js:169:7)
    at Command.parseOptions (/upf/test/node_modules/cucumber/node_modules/commander/index.js:690:14)
    at Command.parse (/upf/test/node_modules/cucumber/node_modules/commander/index.js:455:21)
    at getConfiguration (/upf/test/node_modules/cucumber/lib/cucumber/cli.js:56:13)
    at Object.run (/upf/test/node_modules/cucumber/lib/cucumber/cli.js:69:27)
    at Object.<anonymous> (/upf/test/node_modules/cucumber/bin/cucumber.js:4:5)
    at Module._compile (module.js:409:26)

Can someone please help me in understanding what is wrong with my JSON?

**Comment by ashutoshmittal2309** [comment]
Able to get it to work now. Had to give JSON like this
"{\"debug\": true}"
