### ISSUE TITLE
Errors running the node readme example 

### ISSUE THREAD

**Issue by mcroker** [cucumber/cucumber-js#707]
I am (as a new user) trying to get the node.js example working... https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md

It is generating the following error message
```
features/support/world.js:12
defineSupportCode(function({setWorldConstructor}) {
^

TypeError: defineSupportCode is not a function
    at Object.<anonymous> (/Users/martin/Documents/Dev/lava/pditools/features/support/world.js:12:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (native)
```

I believe that I have correctly copied the code from the nodejs_example and have the correct node dependencies installed.
```
$ npm ls cucumber selenium-webdriver chromedriver
testproject@0.0.1 ./testproject
├── chromedriver@2.25.1 
├── cucumber@1.3.1 
└── selenium-webdriver@3.0.1 
```

Other system info...
```
$ uname -a
Darwin MacBookPro.home 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
$ node -v
v6.9.2
$ npm -v
3.10.9
```

features/documentation.feature 
```
# features/documentation.feature
Feature: Example feature
  As a user of Cucumber.js
  I want to have documentation on Cucumber
  So that I can concentrate on building awesome applications

  Scenario: Reading documentation
    Given I am on the Cucumber.js GitHub repository
    When I click on "CLI"
    Then I should see "Running specific features"
```

features/step_definitions/browser_steps.js
```
// features/step_definitions/browser_steps.js
var seleniumWebdriver = require('selenium-webdriver');
var {defineSupportCode} = require('cucumber');

defineSupportCode(function({Given, When, Then}) {
  Given('I am on the Cucumber.js GitHub repository', function() {
    return this.driver.get('https://github.com/cucumber/cucumber-js/tree/master');
  });

  When('I click on {stringInDoubleQuotes}', function (text) {
    return this.driver.findElement({linkText: text}).then(function(element) {
      return element.click();
    });
  });

  Then('I should see {stringInDoubleQuotes}', function (text) {
    var xpath = "//*[contains(text(),'" + text + "')]";
    var condition = seleniumWebdriver.until.elementLocated({xpath: xpath});
    return this.driver.wait(condition, 5000);
  });
});
```

features/step_definitions/hooks.js
```
// features/step_definitions/hooks.js
var {defineSupportCode} = require('cucumber');

defineSupportCode(function({After}) {
  After(function() {
    return this.driver.quit();
  });
});
```

features/support/world.js
```
// features/support/world.js
require('chromedriver')
var seleniumWebdriver = require('selenium-webdriver');
var {defineSupportCode} = require('cucumber');

function CustomWorld() {
  this.driver = new seleniumWebdriver.Builder()
    .forBrowser('chrome')
    .build();
}

defineSupportCode(function({setWorldConstructor}) {
  setWorldConstructor(CustomWorld)
})
```

**Comment by charlierudolph** [comment]
The example has been updated to support the latest release candidate. I'll update the install command. If you run `npm install --save-dev cucumber@latest` it should work

**Comment by mcroker** [comment]
Works like a dream... many thanks for such a quick response.
