### ISSUE TITLE
Error: TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by coolnixy** [cucumber/cucumber-js#755]
dev dependencies in package.json

 "devDependencies": {
    "appium": "^1.6.3",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-latest": "^6.16.0",
    "babel-register": "^6.18.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "cucumber": "^2.0.0-rc.7",
    "globby": "^6.1.0",
    "mocha": "^3.1.2",
    "mochawesome-screenshots": "^1.4.7",
    "protractor": "^4.0.11",
    "protractor-cucumber-framework": "^0.6.0",
    "rimraf": "^2.5.4",
    "wd": "^1.1.1",
    "wd-bridge": "0.0.2",
    "yargs": "^6.5.0"
  }

My protractor cucumber config file

exports.config = {
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    specs: ['./specs/protractor-cucumber/features/*.feature'],
    cucumberOpts: {
        require: './specs/protractor-cucumber/step-definitions/*.js',
        tags: false,
        format: 'pretty',
        profile: false,
        'no-source': true                      
    },
    capabilities: {
        browserName: 'chrome'
    },
    getPageTimeout: 60000 * 2,
    allScriptsTimeout: 60000 * 2,
    
    onPrepare: function() {

        require('babel-register')({
            "presets": ["latest"]
        });

        let chai = require('chai'),            
            globby = require('globby'),
            rimraf = require('rimraf');

        chai.should();
        chai.use(require('chai-as-promised'));
        global.EC = protractor.ExpectedConditions;        
        browser.driver.manage().window().maximize();
    }
}

When I run the protractor protractor.cucumber.config, I get error

Error: TypeError: Cannot call a class as a function
    at exports.default (D:\Apps.UI.Tests.Copy\node_modules\babel-runtime\helpers\classCallCheck.js:7:11)
    at Object.Cli (D:\Apps.UI.Tests.Copy\node_modules\cucumber\lib\cli\index.js:64:34)
    at D:\Apps.UI.Tests.Copy\node_modules\protractor-cucumber-framework\index.js:31:16
    at Function.promise (D:\Apps.UI.Tests.Copy\node_modules\q\q.js:682:9)
    at D:\Apps.UI.Tests.Copy\node_modules\protractor-cucumber-framework\index.js:24:14
    at _fulfilled (D:\Apps.UI.Tests.Copy\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\Apps.UI.Tests.Copy\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Apps.UI.Tests.Copy\node_modules\q\q.js:796:13)
    at D:\Apps.UI.Tests.Copy\node_modules\q\q.js:556:49
    at runSingle (D:\Apps.UI.Tests.Copy\node_modules\q\q.js:137:13)
    at flush (D:\Apps.UI.Tests.Copy\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[16:51:53] E/launcher - Process exited with error code 100

**Comment by charlierudolph** [comment]
It appears `protractor-cucumber-framework` is not compatible with the 2.0 release candidates of cucumber-js. Please create an issue there
