### ISSUE TITLE
[Question] How can I ignore en empty @rerun.txt file

### ISSUE THREAD

**Issue by asanchezgiraldo** [cucumber/cucumber-js#761]
Currenlty I am trying to run my features in a TeamCity but the environment seems to be flaky and I need to be able to rerun the fail features when this happens.

However, when all of the test fail i want to be able to ignore an empty @rerun.txt file so I can continue with my continues integration.

currently i get the below error

```
fs.js:1568
  return binding.realpath(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, realpath ''
    at Error (native)
    at Object.realpathSync (fs.js:1568:18)
    at Object.expandPathWithExtensions (/Users/alejandro/homes-site/automation/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/path_expander.js:14:23)
    at /Users/alejandro/homes-site/automation/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/path_expander.js:8:27
    at Array.map (native)
    at Object.expandPathsWithExtensions (/Users/alejandro/homes-site/automation/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/path_expander.js:7:31)
    at Object.expandPaths (/Users/alejandro/homes-site/automation/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/feature_path_expander.js:9:38)
    at Function.Configuration (/Users/alejandro/homes-site/automation/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli/configuration.js:21:63)
    at getConfiguration (/Users/alejandro/homes-site/automation/node_modules/chimp/dist/lib/cucumberjs/cucumber-wrapper.js:47:38)
    at Object.run (/Users/alejandro/homes-site/automation/node_modules/chimp/dist/lib/cucumberjs/cucumber-wrapper.js:53:27)
Cucumber steps failed

```
Do you have any suggestions as currenlty when I try to run an empty file I get an error message if it has @ as a suffix?

**Comment by charlierudolph** [comment]
> However, when all of the test fail i want to be able to ignore an empty @rerun.txt file so I can continue with my continues integration.

I don't understand this. If you have failures your rerun file should not be empty. Do you mean when all of the tests pass?

In `2.0.0-rc.0`, we had a bugfix come in that removed empty lines from the rerun formatter I believe addresses this issue. What version are you using?

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed
