### ISSUE TITLE
TypeError at the end of test run: "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by gareth-robinson** [cucumber/cucumber-js#787]
I'm starting to see an error at the end of testing features.

caused by: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1229:5)
    at formatLocation (.../node_modules/cucumber/lib/formatter/utils.js:18:25)
    at PrettyFormatter.logIssue (.../node_modules/cucumber/lib/formatter/summary_formatter.js:201:58)
    at .../node_modules/cucumber/lib/formatter/summary_formatter.js:237:16

Cucumber has a dependency on gherkin ^4.0.0; gherkin v4.1.0 was pushed recently and there appears to be a difference in what the gherkin compiler returns that cucumber-js isn't handling
4.0.0 returns a 'path' element here: https://github.com/cucumber/gherkin-javascript/blob/v4.0.0/lib/gherkin/pickles/compiler.js#L145
4.1.0 does not: https://github.com/cucumber/gherkin-javascript/blob/v4.1.0/lib/gherkin/pickles/compiler.js#L147

**Comment by floribon** [comment]
This has been affecting us as well recently:
```
VError: a handler errored, process exiting: PrettyFormatter::handleFeaturesResult: Path must be a string. Received undefined
```
Once one scenario fail, any following does. It's late here but will get back when there are news.

**Comment by tchaffee** [comment]
+1

**Comment by charlierudolph** [comment]
Thanks for the report! Working on a fix

**Comment by charlierudolph** [comment]
`2.0.0-rc.9` released with the fix

**Comment by midniteio** [comment]
@charlierudolph this implies anything less than `2.0.0-rc.9` is not fully safe to use without knowing to manually go in and pin or shrinkwrap dependencies to 4.0.0. This feels wrong, and that Gherkin version change should have been a major version to not introduce backwards incompatibility with (most) cucumber-js versions.

**Comment by charlierudolph** [comment]
Correct gherkin should have released a breaking change. Nothing we can really do about that. If you are using something like [yarn](https://yarnpkg.com/en/) (or an npm shrinkwrap with the dev dependencies included) you are not liable to break when dependencies of dependencies upgrade.

**Comment by midniteio** [comment]
Yeah absolutely, just more wondering if there's some chance to address by rolling back Gherkin-cucumber's change and having them rerelease on 5.0.0, as both repos are in the same org (though understandably not the same developers) and so would hope there's some room for compromise. Granted this is more a question for those developers and not you.

**Comment by charlierudolph** [comment]
I passed a message onto gherkin about the breaking change. Personally I like the update to not rely on the removed change though anyway

**Comment by aslakhellesoy** [comment]
That's my bad. I released Gherkin 4.1.0 without first verifying that it works with downstream cucumbers. I did consider releasing 5.0.0, but in a moment of poor judgement I decided no APIs had changed, only added.

A workaround for now could be to pin your package.json to gherkin 4.0.0

**Comment by sugo1980** [comment]
I am using the cucumber version 2.0.0-rc.9, but still I am getting the following errror while running my test...

**Comment by sugo1980** [comment]
VError: a handler errored, process exiting: PrettyFormatter::handleFeaturesResult: Path must be a string. Received undefined
    at C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\runtime\event_broadcaster.js:78:21
    at next (native)
    at tryCatcher (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:97:49)
    at Async._drainQueue (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
caused by: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:539:5)
    at formatLocation (C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\formatter\utils.js:18:25)
    at PrettyFormatter.logIssue (C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\formatter\summary_formatter.js:200:58)
    at C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\formatter\summary_formatter.js:236:16
    at Array.forEach (native)
    at PrettyFormatter.logIssues (C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\formatter\summary_formatter.js:235:19)
    at PrettyFormatter.handleFeaturesResult (C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\formatter\summary_formatter.js:133:14)
    at Function.<anonymous> (C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\user_code_runner.js:59:25)
    at next (native)
    at tryCatcher (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:97:49)
    at Function.<anonymous> (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:201:15)
    at Function.run (C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\user_code_runner.js:118:22)
    at C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\runtime\event_broadcaster.js:68:58
    at next (native)
    at tryCatcher (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:201:15
    at C:\item-cache\receiving-item-cache\node_modules\cucumber\lib\runtime\event_broadcaster.js:84:24
    at tryCatcher (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\item-cache\receiving-item-cache\node_modules\cucumber\node_modules\bluebird\js\release\reduce.js:155:18)

**Comment by sugo1980** [comment]
fyi, after reading the above comments I have changed my gherkin version to 4.0.0. Still no luck :-(
