### ISSUE TITLE
E/launcher - Error: TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by piotro83** [cucumber/cucumber-js#795]
new chrome 57 and a big problem: could anybody help me?

` devDependencies": {
    "chai": "~3.5.0",
    "chai-as-promised": "~6.0.0",
    "cucumber": "~1.3.2",
    "cucumber-html-report": "~0.5.6",
    "cucumber-html-reporter": "~0.2.6",
    "grunt-protractor-runner": "~5.0.0",
    "protractor": "~5.1.1",
    "protractor-cucumber": "~0.1.8",
    "protractor-cucumber-framework": "~1.0.2",
    "selenium-webdriver": "~3.3.0",
    ...'
	
	
	'Running "protractor:dev-chrome-smoke" (protractor) task
[21:53:30] I/launcher - Running 1 instances of WebDriver
[21:53:30] I/local - Starting selenium standalone server...
[21:53:31] I/local - Selenium standalone server started at http://192.168.1.9:58532/wd/hub'

 
'E/launcher - Error: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:66:33
    at Array.forEach (native)
    at Object.wrapper (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:62:15)
    at Object.initializer (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:24:41)
    at Object.Library (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\support_code\library.js:133:25)
    at Object.getSupportCodeLibrary (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\cli\configuration.js:128:32)
    at Object.getSupportCodeLibrary (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\runtime.js:44:46)
    at Object.start (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\runtime.js:12:37)
    at Object.run (C:\projects\app\webclient\core\node_modules\cucumber\lib\cucumber\cli.js:75:15)
    at C:\projects\app\webclient\core\node_modules\protractor-cucumber-framework\index.js:33:36
    at Function.promise (C:\projects\app\webclient\core\node_modules\q\q.js:682:9)
    at C:\projects\app\webclient\core\node_modules\protractor-cucumber-framework\index.js:23:14
    at _fulfilled (C:\projects\app\webclient\core\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\projects\app\webclient\core\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\projects\app\webclient\core\node_modules\q\q.js:796:13)
    at C:\projects\app\webclient\core\node_modules\q\q.js:556:49
    at runSingle (C:\projects\app\webclient\core\node_modules\q\q.js:137:13)
    at flush (C:\projects\app\webclient\core\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[21:53:41] E/launcher - Process exited with error code 100
>>
Warning: Tests failed, protractor exited with code: 100 Use --force to continue.

Aborted due to warnings.`

**Comment by charlierudolph** [comment]
Woah. I'm surprised this has never come up so far. I believe this caused by a support file that doesn't export anything.

**Comment by piotro83** [comment]
I'm blocked by chrome 57 update. :(

**Comment by piotro83** [comment]
@charlierudolph maybe you have any proposition to solve the problem?

**Comment by charlierudolph** [comment]
I think this [line](https://github.com/cucumber/cucumber-js/blob/1.x/lib/cucumber/cli/support_code_loader.js#L66) needs to start with a check that `initializer` is an object. Would be great to have a test that captures this error as well. If you would like to submit a PR for this please branch off the "1.x" instead of "master". I don't know how soon I'd be able to get to this so if you could help out that'd be great

**Comment by piotro83** [comment]
problem resolved:

example.js:

```
var example = function () {

some methods...

};
module.exports = example();
```
initializer false because module.exports = example **()**;

i remove () and works fine. eh my mistake.
