### ISSUE TITLE
Cucumber-2 : Callback doesn't get triggered if a chai expect fails

### ISSUE THREAD

**Issue by rakeshkumar5b4** [cucumber/cucumber-js#801]
I am facing an issue in cucumber 2 where callback() fail method doesn't get triggered if the chai expect fails. Instead it throws an error as shown below and the process exits.

```javascript 
[10:06:24] E/launcher - expected false to be true
[10:06:24] E/launcher - AssertionError: expected false to be true
    at doAsserterAsyncAndAddThen (/Users/rakeshkumar/githome/r4e-fe-16587/r4e-e2e/node_modules/chai-as-promised/lib/chai-as-promised.js:293:29)
    at Assertion.<anonymous> (/Users/rakeshkumar/githome/r4e-fe-16587/r4e-e2e/node_modules/chai-as-promised/lib/chai-as-promised.js:283:21)
    at Assertion.get (/Users/rakeshkumar/githome/r4e-fe-16587/r4e-e2e/node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
    at Timeout._onTimeout (/Users/rakeshkumar/githome/r4e-fe-16587/r4e-e2e/repbiz/cucumber/stepDefinitions/cucumber2.steps.js:26:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[10:06:24] E/launcher - Process exited with error code 199
protractor-run closing code: 199

```

Sample program for the same:

```javascript
defineSupportCode(({Given, Then, After, setDefaultTimeout}) => {
  Then(/^Database should be empty$/, function(callback) {
	  setTimeout(function () {
		  expect(false).to.be.true; // if this assertion fails, then the After hook is never called
		  callback();
	  }, 1000);
  });
	
  After(function() {
	  console.log('Cleaning up');
  });
});
```
Packages used:
```code
    "chai": "3.5.0",
    "chai-as-promised": "6.0.0",
    "cucumber": "v2.0.0-rc.8",
    "protractor": "~5.1.0",
```

**Comment by charlierudolph** [comment]
We have tests that cucumber handles this properly. Please create an issue on protractor or whatever you are using to run your test.
