### ISSUE TITLE
Update Implement with the following snippet template

### ISSUE THREAD

**Issue by jludvice** [cucumber/cucumber-js#805]
`cucumber.js` generates following message on unimplemented steps:
```
     Undefined. Implement with the following snippet:

       @given(/^clean application state$/)                                                                                                                          
       public GivenXXX (callback): void {                                                                                                                           
         // Write code here that turns the phrase above into concrete actions                                                                                       
         callback.pending();                                                                                                                                        
       } 
```
But copy-paste and run throws 
```
     TypeError: callback.pending is not a function
         at ConnectionSteps.GivenXXX (/home/jludvice/devel/redhat/ipaas/ipaas-ui/e2e/connections/connections.steps.ts:23:14)
         at World.bindingFunc (/home/jludvice/devel/redhat/ipaas/ipaas-ui/node_modules/cucumber-tsflow/src/BindingDecorator.ts:145:85)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)
```

Replacing `callback.pending()` with `callback(null, 'pending')` seems to work for me.

I'm using cucumber.js on angular2/typescript project.
Does it make sense to update snippet to use `callback(null, 'pending')` ?

**Comment by charlierudolph** [comment]
Those are not the default snippets. I'm guessing you are using a custom snippet syntax and thus need to open an issue on that module
