### ISSUE TITLE
"TypeError: Generator is already running" with cucumber 2.2.0 and protractor-cucumber-framework

### ISSUE THREAD

**Issue by Boxdove** [cucumber/cucumber-js#816]
We use Protractor and cucumber on project. After updating of cucumber to 2.2.0(rc.9) and protractor-cucumber-framework to 3.1.0 I ve got the error "TypeError: Generator is already running"

Environment : Win 7,Node 6.10.2, npm 4.5.0
My code is 
Feature: Bug report feature
 @test
  Scenario: Bug report test
    When I open main page and click login button

(function () {
    var commonSteps = function () {
        this.Given(/^I open main page and click login button$/, function (callback) {
            browser.ignoreSynchronization = true;
            browser.driver.manage().window().maximize();
            var loginButton = element(by.id("ctrlLogin_LoginButton"));
            browser.get('https://irm.ipreo.com/Login.aspx?ReturnUrl=%2f');
            loginButton.click();
            callback();
        });
    }
});

Error is : 

[15:15:38] I/launcher - Running 1 instances of WebDriver
[15:15:38] I/direct - Using ChromeDriver directly...
[15:15:41] E/launcher - BUG: launcher exited with 1 tasks remaining
Unhandled rejection TypeError: Generator is already running
    at throw (native)
    at undefined.tryCatcher (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseRejected (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:107:10)
    at PromiseSpawn._continue (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:158:22)
    at PromiseSpawn._promiseFulfilled (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:99:10)
    at Promise._settlePromise (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\projects\RadiantProtractor\node_modules\cucumber\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

Process finished with exit code 100

![conf](https://cloud.githubusercontent.com/assets/7779816/25179813/24c90a4a-2514-11e7-94e5-4d18105a04d2.png)
![package](https://cloud.githubusercontent.com/assets/7779816/25179812/24c8687e-2514-11e7-9bfc-8a55f4dbe98b.png)

**Comment by charlierudolph** [comment]
Please open your issue on `protractor-cucumber-framework` first. Nothing in your example makes me think the issue is caused by a bug in this project
