### ISSUE TITLE
All page loads time out inside Docker container

### ISSUE THREAD

**Issue by WillemMali** [cucumber/cucumber-js#818]
When running Cucumber-JS with `chromedriver` inside a Docker container (emulating a screen with `xvfb-run` and orchestrated with `docker-compose`), I can't seem to connect to anything, all page loads time out. Chrome also crashes sometimes, but not when I invoke it by hand from the commandline (like `xvfb-run google-chrome http://google.com`). I've also tried running a shell in the container and `curl`ing `google.com` and `ed:9000`, both of which work fine.

Sad log:

```
Attaching to development_cucumber_1
cucumber_1  | Connecting to ED at ed:9000...
cucumber_1  | ED online!
cucumber_1  | 
cucumber_1  | > ed-cucumber-tests@1.0.0 test /opt/cucumber
cucumber_1  | > ./run
cucumber_1  | 
cucumber_1  | Feature: Homepage
cucumber_1  | 
cucumber_1  |   Scenario: Go to login
cucumber_1  | Navigating to: http://ed:9000/
cucumber_1  |   ✖ Given I am on "/"
cucumber_1  |   - When I click on "button#signin"
cucumber_1  |   - Then I should be on "/login"
cucumber_1  | 
cucumber_1  |  <snip>
cucumber_1  | 
cucumber_1  |   Scenario: link goes to homepage
cucumber_1  | Navigating to: http://ed:9000/efqm
cucumber_1  |   ✖ Given I am on "/efqm"
cucumber_1  |   - When I click on "a.navbar-brand.ribbon-wrapper"
cucumber_1  |   - Then I should be on "/"
cucumber_1  | 
cucumber_1  | 
cucumber_1  | Failures:
cucumber_1  | 
cucumber_1  | 1) Scenario: Go to login - features/homepage.feature:6
cucumber_1  |    Step: Given I am on "/" - features/homepage.feature:4
cucumber_1  |    Step Definition: features/step_definitions/browser_steps.js:7
cucumber_1  |    Message:
cucumber_1  |      Error: function timed out after 5000 milliseconds
cucumber_1  |          at Timeout._onTimeout (/opt/cucumber/node_modules/cucumber/lib/user_code_runner.js:91:22)
cucumber_1  |          at ontimeout (timers.js:386:14)
cucumber_1  |          at tryOnTimeout (timers.js:250:5)
cucumber_1  |          at Timer.listOnTimeout (timers.js:214:5)
cucumber_1  | 
cucumber_1  |  <snip>
cucumber_1  | 
cucumber_1  | 11) Scenario: Signup - features/login.feature:10
cucumber_1  |     Step: Given I am on "/login" - features/login.feature:4
cucumber_1  |     Step Definition: features/step_definitions/browser_steps.js:7
cucumber_1  |     Message:
cucumber_1  |       Error: function timed out after 5000 milliseconds
cucumber_1  |           at Timeout._onTimeout (/opt/cucumber/node_modules/cucumber/lib/user_code_runner.js:91:22)
cucumber_1  |           at ontimeout (timers.js:386:14)
cucumber_1  |           at tryOnTimeout (timers.js:250:5)
cucumber_1  |           at Timer.listOnTimeout (timers.js:214:5)
cucumber_1  | 
cucumber_1  | 12) Scenario: Signup - features/login.feature:10
cucumber_1  |     Step: After
cucumber_1  |     Step Definition: features/step_definitions/hooks.js:4
cucumber_1  |     Message:
cucumber_1  |       WebDriverError: unknown error: Chrome failed to start: crashed
cucumber_1  |         (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.16.0-4-amd64 x86_64)
cucumber_1  |           at Object.checkLegacyResponse (/opt/cucumber/node_modules/selenium-webdriver/lib/error.js:517:15)
cucumber_1  |           at parseHttpResponse (/opt/cucumber/node_modules/selenium-webdriver/lib/http.js:516:11)
cucumber_1  |           at doSend.then.response (/opt/cucumber/node_modules/selenium-webdriver/lib/http.js:432:13)
cucumber_1  |           at process._tickCallback (internal/process/next_tick.js:109:7)
cucumber_1  |       From: Task: WebDriver.createSession()
cucumber_1  |           at Function.createSession (/opt/cucumber/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
cucumber_1  |           at Function.createSession (/opt/cucumber/node_modules/selenium-webdriver/chrome.js:709:29)
cucumber_1  |           at createDriver (/opt/cucumber/node_modules/selenium-webdriver/index.js:167:33)
cucumber_1  |           at Builder.build (/opt/cucumber/node_modules/selenium-webdriver/index.js:639:16)
cucumber_1  |           at new CustomWorld (/opt/cucumber/features/support/world.js:10:10)
cucumber_1  |       From: Task: WebDriver.quit()
cucumber_1  |           at thenableWebDriverProxy.schedule (/opt/cucumber/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
cucumber_1  |           at thenableWebDriverProxy.quit (/opt/cucumber/node_modules/selenium-webdriver/lib/webdriver.js:849:23)
cucumber_1  |           at CustomWorld.<anonymous> (/opt/cucumber/features/step_definitions/hooks.js:5:28)
cucumber_1  | 
cucumber_1  | 13) Scenario: link goes to homepage - features/logo.feature:10
cucumber_1  |     Step: Given I am on "/" - features/logo.feature:4
cucumber_1  |     Step Definition: features/step_definitions/browser_steps.js:7
cucumber_1  |     Message:
cucumber_1  |       Error: function timed out after 5000 milliseconds
cucumber_1  |           at Timeout._onTimeout (/opt/cucumber/node_modules/cucumber/lib/user_code_runner.js:91:22)
cucumber_1  |           at ontimeout (timers.js:386:14)
cucumber_1  |           at tryOnTimeout (timers.js:250:5)
cucumber_1  |           at Timer.listOnTimeout (timers.js:214:5)
cucumber_1  | 
cucumber_1  |  <snip>
cucumber_1  | 
cucumber_1  | 23) Scenario: Signup - features/network.feature:8
cucumber_1  |     Step: When I click on "Signup here" - features/network.feature:9
cucumber_1  |     Step Definition: features/step_definitions/browser_steps.js:18
cucumber_1  |     Message:
cucumber_1  |       Error: function timed out after 5000 milliseconds
cucumber_1  |           at Timeout._onTimeout (/opt/cucumber/node_modules/cucumber/lib/user_code_runner.js:91:22)
cucumber_1  |           at ontimeout (timers.js:386:14)
cucumber_1  |           at tryOnTimeout (timers.js:250:5)
cucumber_1  |           at Timer.listOnTimeout (timers.js:214:5)
cucumber_1  | 
cucumber_1  | 24) Scenario: Signup - features/network.feature:8
cucumber_1  |     Step: After
cucumber_1  |     Step Definition: features/step_definitions/hooks.js:4
cucumber_1  |     Message:
cucumber_1  |       WebDriverError: unknown error: Chrome failed to start: crashed
cucumber_1  |         (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.16.0-4-amd64 x86_64)
cucumber_1  |           at Object.checkLegacyResponse (/opt/cucumber/node_modules/selenium-webdriver/lib/error.js:517:15)
cucumber_1  |           at parseHttpResponse (/opt/cucumber/node_modules/selenium-webdriver/lib/http.js:516:11)
cucumber_1  |           at doSend.then.response (/opt/cucumber/node_modules/selenium-webdriver/lib/http.js:432:13)
cucumber_1  |           at process._tickCallback (internal/process/next_tick.js:109:7)
cucumber_1  |       From: Task: WebDriver.createSession()
cucumber_1  |           at Function.createSession (/opt/cucumber/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
cucumber_1  |           at Function.createSession (/opt/cucumber/node_modules/selenium-webdriver/chrome.js:709:29)
cucumber_1  |           at createDriver (/opt/cucumber/node_modules/selenium-webdriver/index.js:167:33)
cucumber_1  |           at Builder.build (/opt/cucumber/node_modules/selenium-webdriver/index.js:639:16)
cucumber_1  |           at new CustomWorld (/opt/cucumber/features/support/world.js:10:10)
cucumber_1  |       From: Task: WebDriver.quit()
cucumber_1  |           at thenableWebDriverProxy.schedule (/opt/cucumber/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
cucumber_1  |           at thenableWebDriverProxy.quit (/opt/cucumber/node_modules/selenium-webdriver/lib/webdriver.js:849:23)
cucumber_1  |           at CustomWorld.<anonymous> (/opt/cucumber/features/step_definitions/hooks.js:5:28)
cucumber_1  | 
cucumber_1  | 12 scenarios (12 failed)
cucumber_1  | 34 steps (12 failed, 22 skipped)
cucumber_1  | 2m00.070s
cucumber_1  | npm ERR! Test failed.  See above for more details.
cucumber_1  | idling for debugging purposes
compose.mk:121: recipe for target 'cucumber-logs' failed
```

An example from my features:

```
Feature: Login Page

  Background:
    Given I am on "/login"

  Scenario: Forgot Password?
    When I click on "Forgot Password?"
    Then I should be on "/forgot"
```

My support code:

```
var webdriver = require('selenium-webdriver');
var {defineSupportCode} = require('cucumber');
var By = webdriver.By;
var until = webdriver.until;

defineSupportCode(function({Given, When, Then}) {
    Given('I am on {stringInDoubleQuotes}', function(relativeUrl) {
        var initialUrl = this.baseUrl + relativeUrl;
        console.log("Navigating to: " + initialUrl)
        return this.driver.get(initialUrl);
    });

    <snip>

});
```

How I call `cucumber.js`:

```
#!/bin/sh -eu

xvfb-run -s '-screen 0 1280x1024x8' \
node_modules/cucumber/bin/cucumber.js \
    `#echo --fail-fast` \
    --world-parameters='{
      "baseUrl": "http://ed:9000"
    }';
```

My `package.json`:

```
{
  "name": "ed-cucumber-tests",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "./run"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chromedriver": "^2.29.0",
    "cucumber": "^2.0.0-rc.9",
    "selenium-webdriver": "^3.3.0",
    "uuid": "^3.0.1"
  }
}
```

I'm on Debian 8, using the official Debian 8 Docker image and the official Google Chrome installation instructions.

**Comment by WillemMali** [comment]
I'm working on a minimal example but it's currently blocked by [`docker` being broken.](https://github.com/moby/moby/issues/32764), this isn't a good day.

**Comment by charlierudolph** [comment]
We have a working [nodejs example](https://github.com/cucumber/cucumber-js/blob/v2.0.0-rc.9/docs/nodejs_example.md) that use chromedriver that is not in docker. Based on that I don't expect this to be a cucumber issue. You can always increase the step timeout as well.

**Comment by WillemMali** [comment]
Fair enough, this looks more like an issue with `chromedriver` or even `chrome` not working inside Docker.
