### ISSUE TITLE
Running `npm test` results in errors

### ISSUE THREAD

**Issue by nicojs** [cucumber/cucumber-js#826]
After checking out the cucumber-js repository and running `yarn install` on my windows machine i can't run `npm t` without errors. 

First errors had to do with line endings.

```bash
   ...
  76:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 7808 problems (7808 errors, 0 warnings)
```

I'm planning to add a `.gitattributes` file in a PR to resolve this issue (not being depended on the global git settings of windows users).

After fixing that, i'm able to run the mocha unit tests without problems. However this step is giving a lot of errors:

```bash
$ node ./bin/cucumber.js
...--FF----...
...
348) Scenario: custom world constructor is passed the parameters - features\world_parameters.feature:80
     Step: After
     Step Definition: features\support\hooks.js:42
     Message:
       TypeError: Cannot read property 'error' of undefined
           at World.<anonymous> (C:/z/github/cucumber/cucumber-js/features/support/hooks.js:43:9)
           at Function.<anonymous> (C:\z\github\cucumber\cucumber-js\lib\user_code_runner.js:59:25)
...
174 scenarios (174 failed)
851 steps (851 skipped)
0m01.087s
```

My system information:

```
$ systeminfo | grep 'OS Name\|OS Version'
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393

$ npm --version
3.8.2

$ node --version
v7.5.0

$ yarn --version
0.23.4
```

**Comment by nicojs** [comment]
For the first issue: #827

**Comment by charlierudolph** [comment]
Hey @nicojs thanks for trying out development on windows! I've been working on a mac so haven't run into these issues. I had hoped appveyor ci would make these types of issues visible.

One note: please use `yarn test` instead of `npm test`.

With regards to the feature tests: the after hook appears to be erroring [here](https://github.com/cucumber/cucumber-js/blob/7800ed30b435cbf65cc932f44ce7114e7356e125/features/support/hooks.js#L43) where I'm guessing `this.lastRun` is undefined. Are you seeing another error? Something else is probably going wrong as I believe all scenarios should define `lastRun` at some point.  

You also appear to be running the feature tests by hand with `node ./bin/cucumber.js`. Did you also compile the code first (see the `prefeature-test` script in the `package.json`)?

**Comment by nicojs** [comment]
#827 tis is the PR

**Comment by nicojs** [comment]
> With regards to the feature tests: the after hook appears to be erroring here where I'm guessing this.lastRun is undefined. Are you seeing another error? Something else is probably going wrong as I believe all scenarios should define lastRun at some point.

This is indeed the issue. If i scroll up i see the real error:

```bash
Error: EPERM: operation not permitted, symlink 'C:\z\github\cucumber\cucumber-js\.babelrc' -> 'C:\Users\nicoj\AppData\Local\Temp\tmp-17340zCWUs05Oz6v1\.babelrc'
```

Symlinking seems to only work when running under an admin command prompt on windows:
https://github.com/nodejs/node-v0.x-archive/issues/6342

If i run the command in an elevated command prompt it works. Probably this is what your appveyor build does as well. 

I think this should be mentioned somewhere or ideally run as non-admin as well. Having to run as admin is not what you want as a contributor.

**Comment by charlierudolph** [comment]
Could you try out switching out the symlink in the test setup for: https://github.com/broccolijs/node-symlink-or-copy?

**Comment by nicojs** [comment]
Do you really want that as a solution? Wouldn't that mean copying over the entire node_modules folder to a new temp folder before each scenario?

https://github.com/cucumber/cucumber-js/blob/master/features/support/hooks.js#L32

I was thinking maybe create a sub folder `.cucumber-tmp` where you copy over each scenario. That way node resolution would still work. We use this solution to create sandboxes for running tests in [stryker](https://stryker-mutator.github.io).

**Comment by Izhaki** [comment]
Closing due to inactivity.

If the issue still exists / is important we'll re-open.
