### ISSUE TITLE
How to generate HTML report with v2.0

### ISSUE THREAD

**Issue by fredgate** [cucumber/cucumber-js#832]
When I use the `format` option and set it to `json`, then a JSON file is successfully generated at the end of the test campaign.
But when I set the `format` option to `html`, an error immediatly occurs :
```
Unhandled rejection Error: Cannot find module 'C:\XXXX\my-project\html'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.loadCustomFormatter (C:\Almerys\Protractor\cucumber-quickstart\node_modules\cucumber\lib\formatter\builder.js:135:29)
    at Function.getConstructorByType (C:\Almerys\Protractor\cucumber-quickstart\node_modules\cucumber\lib\formatter\builder.js:105:35)
```
It seems normal as in the V2 of cucumber, there is no biult-in formatter for HTML.
So how to do ?

**Comment by charlierudolph** [comment]
Please see https://github.com/cucumber/cucumber-js/issues/94#issuecomment-243031808
