### ISSUE TITLE
Process exited with error code 199

### ISSUE THREAD

**Issue by pnakhat** [cucumber/cucumber-js#835]
HI,

I am using cuucmber js with protractor versions below
    "cucumber": "^2.1.0",
    "cucumber-html-reporter": "^0.4.2",
    "protractor": "^5.1.0",
    "protractor-cucumber-framework": "^3.1.0"

When a test fails lets day not finding an element , cucumber stops abruptly with below errors. It doesn't trigger any hooks. Happy path seems to be working fine.

    Given('I am on google search page',function(next){
         browser.get("http://www.google.co.uk");
         next();
        // element(by.id('q')).sendKeys("test");
    });

    When(/^I search for "([^"]*)"$/, function(arg1, next) {
        // Write code here that turns the phrase above into concrete actions
        element(by.name('q')).sendKeys(arg1);
        element(by.name('q11')).submit().then(next);
    });

});`

  V Given I am on google search page
[14:30:44] E/launcher - No element found using locator: By(css selector, *[name="q11"])
[14:30:44] E/launcher - NoSuchElementError: No element found using locator: By(css selector, *[name="q11"])
    at WebDriverError (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\error.js:27:5)
    at NoSuchElementError (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\error.js:168:5)
    at elementArrayFinder.getWebElements.then (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:851:17)
    at ManagedPromise.invokeCallback_ (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\code\cucumber-js\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)Error
    at ElementArrayFinder.applyAction_ (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:482:23)
    at ElementArrayFinder.(anonymous function) [as submit] (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:96:21
    at ElementFinder.(anonymous function) [as submit] (C:\code\cucumber-js\node_modules\protractor\lib\element.ts:873:14)
    at World.<anonymous> (C:\code\cucumber-js\features\step_definitions\browser_steps.js:17:33)
[14:30:44] E/launcher - Process exited with error code 199
npm ERR! Test failed.  See above for more details.

**Comment by charlierudolph** [comment]
Focusing on the following line:
```javascript
element(by.name('q11')).submit().then(next);
```
it appears that you are passing an error callback. I think that line needs to be updated to
```javascript
element(by.name('q11')).submit().then(next, next);
```

**Comment by pnakhat** [comment]
I changed that, still same issue

**Comment by charlierudolph** [comment]
cucumber should only exit with status 0 or 1 unless there is some uncaught error that is thrown outside of a step definition. Have you opened an issue on protractor-cucumber-framework?

**Comment by pnakhat** [comment]
No, as I am not sure if that's the issue with protractor-cucumber-framework?

**Comment by charlierudolph** [comment]
As part of the [cucumber issue template](https://raw.githubusercontent.com/cucumber/cucumber-js/master/.github/issue_template.md) it asks to please open the issue on the related library first. I don't know what else could cause the issue aside from what I have already suggested.

**Comment by pnakhat** [comment]
If I do this, it works fine 

        element(by.name('q')).submit().then(next).catch(next);

**Comment by charlierudolph** [comment]
Good to hear. I'm surprised protractor's `.then` doesn't support what I thought was the promise standard of being able to accept two arguments (first is onFulfill, second is onReject)
