### ISSUE TITLE
Running cucumber tests by npm run ends with ELIFECYCLE 

### ISSUE THREAD

**Issue by raynox** [cucumber/cucumber-js#843]
OS: macOS Sierra 10.12.4
Node: v7.9.0
Npm: 5.0.0
Cucumber-js: 2.2.0

Hi,

i have a problem with running a cucumber. I have a feature file like this:

```
# language: en
Feature: adding a paid advertisement

  @web-test
  Scenario: adding an advertisement
    Given i am on the main page
    When i click on the add an advertisement button
    Then i should see a form to add an advertisement
```

and step definitions:

```
"use strict";
var defineSupportCode = require('cucumber').defineSupportCode;

defineSupportCode(function ({Given, When, Then}) {

    Given(/^I am on the main page$/, function (callback) {
        callback(null, 'pending');
    });
    When(/^I click on the add an advertisement button$/, function (callback) {
        callback(null, 'pending');
    });
    Then(/^I should see a form to add an advertisement$/, function (callback) {
        callback(null, 'pending');
    });
});
```

When I trigger cucumber test by typing node ./node_modules/.bin/cucumber-js -f pretty -f json:report/json/cucumber_report.json in terminal everything is fine. But when I trigger it by npm run (same script as above but in package.json) it ends with the error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.0.1 bdd-test: `node ./node_modules/.bin/cucumber-js -f pretty -f json:report/json/cucumber_report.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-app@0.0.1 bdd-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p24/.npm/_logs/2017-05-31T21_37_26_376Z-debug.log
```

debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bdd-test' ]
2 info using npm@5.0.0
3 info using node@v7.9.0
4 verbose run-script [ 'prebdd-test', 'bdd-test', 'postbdd-test' ]
5 info lifecycle test-app@0.0.1~prebdd-test: test-app@0.0.1
6 silly lifecycle test-app@0.0.1~prebdd-test: no script for prebdd-test, continuing
7 info lifecycle test-app@0.0.1~bdd-test: test-app@0.0.1
8 verbose lifecycle test-app@0.0.1~bdd-test: unsafe-perm in lifecycle true
9 verbose lifecycle test-app@0.0.1~bdd-test: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/p24/PhpstormProjects/alex-angular2/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle test-app@0.0.1~bdd-test: CWD: /Users/p24/PhpstormProjects/alex-angular2
11 silly lifecycle test-app@0.0.1~bdd-test: Args: [ '-c',
11 silly lifecycle   'node ./node_modules/.bin/cucumber-js -f pretty -f json:report/json/cucumber_report.json' ]
12 silly lifecycle test-app@0.0.1~bdd-test: Returned: code: 1  signal: null
13 info lifecycle test-app@0.0.1~bdd-test: Failed to exec bdd-test script
14 verbose stack Error: test-app@0.0.1 bdd-test: `node ./node_modules/.bin/cucumber-js -f pretty -f json:report/json/cucumber_report.json`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid test-app@0.0.1
16 verbose cwd /Users/p24/PhpstormProjects/alex-angular2
17 verbose Darwin 16.5.0
18 verbose argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "bdd-test"
19 verbose node v7.9.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error test-app@0.0.1 bdd-test: `node ./node_modules/.bin/cucumber-js -f pretty -f json:report/json/cucumber_report.json`
23 error Exit status 1
24 error Failed at the test-app@0.0.1 bdd-test script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

The error does not occurs when I replace callback(null, 'pending') with just callback(). But then I can not mark my tests as pending. I have tried use synchronous and promise snippets but with the same result. 

Also I want to ask if there is a better way to use the TypeScript files to write the step definitions than just compiling them to JavaScript right before the cucumber tests.

**Comment by charlierudolph** [comment]
`npm` prints out the verbose output because cucumber-js exits with status 1 as part of the test script. 

cucumber-js exits with status 1 if there are any undefined / pending / failed / ambiguous steps. It exits with status 0 if all steps pass.

---

Also I want to ask if there is a better way to use the TypeScript files to write the step definitions than just compiling them to JavaScript right before the cucumber tests.

See the [docs](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#transpilers)

**Comment by gkushang** [comment]
@charlierudolph Can you ignore the `Pending` steps failures, or can you avoid to exist with status 1 when steps are undefined / pending / failed / ambiguous?

**Comment by gkushang** [comment]
@charlierudolph 

Please ignore the above question. I just found the option to pass `--no-strict`

Thanks!
