### ISSUE TITLE
Cannot work on nvm

### ISSUE THREAD

**Issue by ee01** [cucumber/cucumber-js#858]
I install node 8.1.2 via nvm.
If I install cucumber globally, It appeared a error message said "Cannot find module 'cucumber'" when I run cucumber-js.
But it work well on normal nodejs without nvm.

> Error: Cannot find module 'cucumber' from '/Users/esone.qiu'
    at /Users/esone.qiu/git/nvm/versions/node/v8.1.2/lib/node_modules/cucumber/node_modules/resolve/lib/async.js:48:31
    at processDirs (/Users/esone.qiu/git/nvm/versions/node/v8.1.2/lib/node_modules/cucumber/node_modules/resolve/lib/async.js:182:39)
    at ondir (/Users/esone.qiu/git/nvm/versions/node/v8.1.2/lib/node_modules/cucumber/node_modules/resolve/lib/async.js:197:13)
    at load (/Users/esone.qiu/git/nvm/versions/node/v8.1.2/lib/node_modules/cucumber/node_modules/resolve/lib/async.js:80:43)
    at onex (/Users/esone.qiu/git/nvm/versions/node/v8.1.2/lib/node_modules/cucumber/node_modules/resolve/lib/async.js:105:17)
    at /Users/esone.qiu/git/nvm/versions/node/v8.1.2/lib/node_modules/cucumber/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by charlierudolph** [comment]
cucumber-js cannot be used with a globally install because you need to require cucumber in your support files and global installed modules cannot be required.

**Comment by ee01** [comment]
@charlierudolph This is found on CTI page.

If you installed Cucumber.js **globally**, you may run it with:

$ cucumber.js
If you installed Cucumber locally, you may need to specify the path to the executable:

$ ./node_modules/.bin/cucumber.js

**Comment by charlierudolph** [comment]
Thanks for pointing that out! I updated the documentation.
