### ISSUE TITLE
Can get Cucumber & Protractor to work in one project but not another

### ISSUE THREAD

**Issue by FarhadG** [cucumber/cucumber-js#887]
I have two Angular applications with nearly the same exact Protractor/Cucumber configurations. One, however, does use ES6 with Webpack while the other is uses Grunt and a typical server (not that these would matter).

I have the same exact test and feature files in both but I get the following error in the more modern application with Webpack, ES6, etc.

- Error: 
```bash
(node:10580) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[13:17:06] I/launcher - Running 1 instances of WebDriver
[13:17:06] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:17:06] W/runner - Ignoring unknown extra flags: compiler. This will be an error in future versions, please use --disableChecks flag to disable the  Protractor CLI flag checks.
[13:17:07] E/launcher - Error: TypeError: Cannot call a class as a function
    at exports.default (/Users/OSX/Code/mckinsey/aimme-frontend/node_modules/babel-runtime/helpers/classCallCheck.js:7:11)
    at Object.Cli (/Users/OSX/Code/mckinsey/aimme-frontend/node_modules/cucumber/lib/cli/index.js:64:34)
    at /Users/OSX/Code/mckinsey/aimme-frontend/node_modules/protractor-cucumber-framework/index.js:31:16
    at Function.promise (/Users/OSX/Code/mckinsey/aimme-frontend/node_modules/q/q.js:702:9)
    at /Users/OSX/Code/mckinsey/aimme-frontend/node_modules/protractor-cucumber-framework/index.js:24:14
    at _fulfilled (/Users/OSX/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/OSX/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/OSX/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/OSX/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/OSX/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/OSX/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[13:17:07] E/launcher - Process exited with error code 100
```

- Dependencies:
```json
    "cucumber": "^0.10.2",
    "protractor": "^3.3.0",
    "protractor-cucumber-framework": "^0.5.0"
```

- protractor.conf.js
```js
exports.config = {
  baseUrl: 'http://localhost:8000/',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: [
    'tests/features/**/*.feature'
  ],
  capabilities: {
    browserName: 'chrome'
  },
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  cucumberOpts: {
    format: 'pretty',
    require: 'tests/features/**/*.js',
  },
};
```

**Comment by charlierudolph** [comment]
Have you opened an issue on `protractor-cucumber-framework` (at the issue template suggested)? You should only open an issue here if its been verified cucumber is the issue and not the wrapping framework.

**Comment by charlierudolph** [comment]
You are also on a very old version of cucumber

**Comment by FarhadG** [comment]
Closing this due to a sub-dependency in the second application causing an issue. So, have decided to separate our test suite from our application suite for now.
