### ISSUE TITLE
Handler error while generating JSON output when Cucumber run in parallel

### ISSUE THREAD

**Issue by arjunjh10** [cucumber/cucumber-js#890]
Hello, I am executing cucumber in parallel for 2 different configurations. I was trying to generate cucumber result output in JSON format for my reporter using `--format` option in CLI. My json files get created, my external html reporter properly generates the report as well, however, I keep getting this error in my console output when I run my scenarios:

```
VError: a handler errored, process exiting: client/tests/ui/features/support/hooks.ts:107: client/tests/ui/features/output/cucumber1.json: Unexpected end of JSON input
    at /Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/event_broadcaster.js:78:21
    at Generator.next (<anonymous>)
From previous event:
    at /Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/event_broadcaster.js:84:24
From previous event:
    at EventBroadcaster.broadcastEvent (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/event_broadcaster.js:61:33)
    at EventBroadcaster.<anonymous> (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/event_broadcaster.js:47:20)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at EventBroadcaster.broadcastAroundEvent (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/event_broadcaster.js:51:22)
    at FeaturesRunner.<anonymous> (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/features_runner.js:63:37)
    at Generator.next (<anonymous>)
From previous event:
    at FeaturesRunner.run (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/features_runner.js:71:22)
    at Runtime.<anonymous> (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/index.js:66:43)
    at Generator.next (<anonymous>)
From previous event:
    at Runtime.start (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/runtime/index.js:76:22)
    at Cli.<anonymous> (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/cli/index.js:164:36)
From previous event:
    at Cli.run (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/cli/index.js:170:22)
    at Object.<anonymous> (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/cli/run.js:44:27)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.run [as default] (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/lib/cli/run.js:63:17)
    at Object.<anonymous> (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/cucumber/bin/cucumber.js:3:37)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
caused by: SyntaxError: client/tests/ui/features/output/cucumber1.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/Users/arjunjhawar/repository/src/account.myfoodbag.co.nz/node_modules/jsonfile/index.js:69:17)
```
I am creating my files like this in my `cucumber.js` file:

```
const jsonFile = `client/tests/ui/features/output/cucumber${process.env.TASK_ID}.json`;
const common = `--format json:${jsonFile} --compiler ts:ts-node/register --tags @test`;
module.exports = {
  build: common,
  'default': common
};
```

TASK_ID is the id number of my browser capability: Running cucumber in parallel for 2 browsers.
And finally after the test run, generating the output html report like this:

```
registerHandler('AfterFeatures', () => {
    const options = {
      theme: 'bootstrap',
      // jsonFile: `${outputDir}test-report.html.json`,
      jsonDir: `${outputDir}`,
      output: `${outputDir}test-report.html`,
      reportSuiteAsScenarsios: true,
      launchReport: false,
      ignoreBadJsonFile:true,
      storeScreenShots: true,
      metadata: {
        'Browser': capabilities.browserName,
        'Platform': capabilities.os,
        'Browser_version': capabilities.browser_version,
        'Resolution': capabilities.resolution,
        'Run-On': 'Browserstack'
      }
    };

    reporter.generate(options);
  });
```

Since I am using the `--format` option, therefore I am not sure why the error is reporting that the file has some error. Please help. Thank you.

**Comment by Frankusky** [comment]
I got the same issue before, this is because the AfterFeatures event is fired each time a feature ends, so after the first feature ends it will try to parse the JSON but actually is not complete since the other configuration it still in progress.

At version 3.0.0 they implemented [AfterAll and BeforeAll](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#beforeall--afterall) methods that will solve your issue.

**Comment by mucsi96** [comment]
I have tested the AfterAll hook for parsing the Cucumber JSON report. The report is not created yet at that time. :(

**Comment by arjunjh10** [comment]
@mucsi96 Can you please share a snippet of how you managed it in the node process? :)

**Comment by arjunjh10** [comment]
@Frankusky Yeah. But even with AfterAll and BeforeAll hooks, they'd fire after a parallel run ends, so it might still cause the issue.

**Comment by charlierudolph** [comment]
> So my solution was to parse the report in a separate node process after the cucumber execution has finished.

Please do that. The hooks are meant for help in running the tests. Please parse the formatting results by piping them into something else or running a command after cucumber-js finishes running
