### ISSUE TITLE
After upgrade to 3.0.3 I received an error for Undefined parameter type

### ISSUE THREAD

**Issue by Syslog2905** [cucumber/cucumber-js#934]
I'm using cucumber with protractor and java script for step implementations.
The failing step is:

Given I go to URL /insis/

//GIVEN steps
  Given('I go to URL {url}', function (url, callback) {
    browser.get(url);
    callback();
  });

I've changed the step to:
Given I go to URL http://192.168.2.252:7801/insis/
by changing params in protractor.conf.js:
 prefs: {
    // Disable Chrome's annoying password manager
    'profile.password_manager_enabled': true,
    'credentials_enable_service': true,
    'password_manager_enabled': true
  },

  baseUrl: 'http://192.168.2.252:7801/insis/', so that I do not append /insis/ part anymore but the error is still there.

Here is the result after my run:
> insis-ui@0.0.0 ptr C:\insis\insis-ui
> protractor protractor.conf.js

[17:40:31] I/launcher - Running 1 instances of WebDriver
[17:40:31] I/local - Starting selenium standalone server...
[17:40:31] I/local - Selenium standalone server started at http://10.32.170.64:49209/wd/hub
Unhandled rejection Error: Undefined parameter type {url}
    at UndefinedParameterTypeError.Error (native)
    at UndefinedParameterTypeError.CucumberExpressionError (C:\insis\insis-ui\node_modules\cucumber-expressions\dist\errors.js:17:131)
    at new UndefinedParameterTypeError (C:\insis\insis-ui\node_modules\cucumber-expressions\dist\errors.js:67:139)
    at new CucumberExpression (C:\insis\insis-ui\node_modules\cucumber-expressions\dist\cucumber_expression.js:45:33)
    at StepDefinition.getCucumberExpression (C:\insis\insis-ui\node_modules\cucumber\src\models\step_definition.js:52:14)
    at StepDefinition.matchesStepName (C:\insis\insis-ui\node_modules\cucumber\src\models\step_definition.js:63:37)
    at C:\insis\insis-ui\node_modules\cucumber\src\runtime\test_case_runner.js:99:29
    at Array.filter (native)
    at TestCaseRunner.getStepDefinitions (C:\insis\insis-ui\node_modules\cucumber\src\runtime\test_case_runner.js:98:52)
    at C:\insis\insis-ui\node_modules\cucumber\src\runtime\test_case_runner.js:61:36
    at Array.forEach (native)
    at TestCaseRunner.emitPrepared (C:\insis\insis-ui\node_modules\cucumber\src\runtime\test_case_runner.js:60:32)
    at TestCaseRunner.<anonymous> (C:\insis\insis-ui\node_modules\cucumber\src\runtime\test_case_runner.js:154:10)
    at next (native)
    at undefined.tryCatcher (C:\insis\insis-ui\node_modules\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\insis\insis-ui\node_modules\cucumber\node_modules\bluebird\js\release\generators.js:97:49)

Here are the snippets of code where errors occur:

1) This is from \node_modules\cucumber-expressions\dist\errors.js:17:131

var CucumberExpressionError = function (_Error) {
  _inherits(CucumberExpressionError, _Error);

  function CucumberExpressionError() {
    _classCallCheck(this, CucumberExpressionError);

    return _possibleConstructorReturn(this, (CucumberExpressionError.__proto__ || Object.getPrototypeOf(CucumberExpressionError)).apply(this, arguments));
  }

2. This is the code from node_modules\cucumber-expressions\dist\cucumber_expression.js:45:33:

 while ((match = PARAMETER_REGEXP.exec(expression)) !== null) {
      var typeName = match[1];

      var parameterType = parameterTypeRegistry.lookupByTypeName(typeName);
      if (!parameterType) throw new UndefinedParameterTypeError(typeName);
      this._parameterTypes.push(parameterType);

      var text = expression.slice(matchOffset, match.index);
      var captureRegexp = buildCaptureRegexp(parameterType.regexps);
      matchOffset = PARAMETER_REGEXP.lastIndex;
      regexp += text;
      regexp += captureRegexp;
    }
    regexp += expression.slice(matchOffset);
    regexp += '$';
    this._treeRegexp = new TreeRegexp(regexp);
  }

Please help, I haven't any clue for the moment. Thanks in advance!

**Comment by gd46** [comment]
Did you create a custom parameter type? Url is not one by default. You need something like this in your support directory. 

Given the following file in support directory

```
let { defineSupportCode } = require('cucumber');

defineSupportCode(({ defineParameterType }) => {
	defineParameterType({
		regexp    		: /url/,
		transformer	: (s) => s.toUpperCase(),
		name    				: 'url'
	});
});
```
You need a regex pattern to match the url or urls etc. You can optionally transform this, so you could pass in something like: 

google.com

and transform it to add www. in front of it or something. The name property is what cucumber is looking for when it says you have an undefined parameter type.

**Comment by Syslog2905** [comment]
Thanks! In fact I'll go with more simple solution to use "string" parameter type like this:

 Given('I go to URL {string}', function (url, callback) {
    browser.get(url);
    callback();
  });

It works fine for now.
