### ISSUE TITLE
"Error: empty stack" on startup - regression in 3.0.4 and above

### ISSUE THREAD

**Issue by mobidev111** [cucumber/cucumber-js#961]
The following error stack trace appears after upgrading an otherwise unchanged project to cucumber-js 3.0.4 (from cucumber-js 3.0.2):

```
Unhandled rejection Error: empty stack
    at pop (/demo/node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:82:35)
    at TagExpressionParser.parse (/demo/node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:52:16)
    at new PickleFilter (/demo/node_modules/cucumber/src/pickle_filter.js:14:52)
    at Cli.<anonymous> (/demo/node_modules/cucumber/src/cli/index.js:90:21)
    at next (native)
    at undefined.tryCatcher (/demo/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/demo/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/demo/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/demo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/demo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/demo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/demo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/demo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

The following case causes the error in tag_expression_parser.js - may it helps with debugging:
```
infix:  ()
tokens:  [ '(', ')' ]
exprs:  []
```

Any other information that I should provide to get this fixed?

**Comment by charlierudolph** [comment]
3.0.4 made the `--tags` option repeatable (joined with and's) when previously it would overwrite. I think this may be the cause of your issue. What command are you using to run and what is in your `cucumber.js` file (if you have one)?

**Comment by mobidev111** [comment]
A (now) invalid 'tags' setting was the cause. Using protractor-cucumber-framework, there are multiple docs on the internet propagating "tags: false" - removing this config line in case of not using tags solves this.

```
cucumberOpts: {
...
tags: false,
...
},
```
